/* This SPSS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\mongolia v4.2.dat" LRECL=297

DATA LIST FILE=DATA/
   COUNTRY 1                IDNUMBER 2-5             LEVEL1 6              
   LEVEL3 7                 YRSURVEY 8-11            ANK_NUM 12-13         
   SE002 14                 SE003 15-16              SE003A 17             
   SE004 18                 SE004A 19                SE005 20-21           
   SE005A 22-25             SE005B 26                SE005C 27             
   SE006 28-29              SE006A 30                SE007 31              
   SE008A 32-33             SE008B 34                SE009 35              
   SE009D 36                SE009B 37                SE009A 38             
   SE009A_1 39              SE009A_2 40              SE009A_3 41           
   SE012A 42                SE012BMO 43-44           SE014 45              
   SE016 46-48              SE016A 49                SE017 50              
   RELIG1 51-52             FGNUM 53                 PGNUM 54              
   Q001 55                  Q002 56                  Q003 57               
   Q004 58                  Q005 59                  Q006 60               
   Q007 61                  Q008 62                  Q009 63               
   Q010 64                  Q011 65                  Q012 66               
   Q013 67                  Q014 68                  Q015 69               
   Q016 70                  Q017 71                  Q018 72               
   Q018_6 73                Q019 74                  Q019_1 75-76          
   Q019_2 77-78             Q019_3 79-80             Q020 81               
   Q020_1 82-83             Q020_2 84                Q020_3 85-86          
   Q021 87-88               Q022 89                  Q023 90               
   Q024 91                  Q025 92                  Q026 93               
   Q027 94                  Q028 95-97               Q029 98               
   Q030 99                  Q031 100                 Q032 101              
   Q033 102                 Q034 103                 Q035 104              
   Q036 105                 Q037 106                 Q038 107              
   Q039 108                 Q040 109                 Q041 110              
   Q042 111                 Q043 112                 Q044 113              
   Q045 114                 Q046 115                 Q047 116              
   Q048 117                 Q049 118                 Q050 119              
   Q051 120                 Q052 121                 Q053 122              
   Q054 123                 Q055 124                 Q056 125              
   Q057 126                 Q057A 127                Q058 128              
   Q059 129                 Q060 130                 Q061 131              
   Q062 132-134             Q063 135                 Q064 136              
   Q065 137                 Q066 138                 Q067 139              
   Q068 140                 Q069 141                 Q070 142              
   Q071 143                 Q072 144                 Q073 145              
   Q074 146                 Q075 147                 Q076 148              
   Q077 149                 Q078 150                 Q079 151              
   Q080 152                 Q081 153                 Q082 154              
   Q083 155                 Q084 156                 Q085 157              
   Q086 158                 Q087 159                 Q088 160              
   Q089 161                 Q090 162                 Q091 163              
   Q092 164                 Q093 165                 Q094 166              
   Q095 167                 Q096 168                 Q097_1 169-171        
   Q097_2 172-174           Q097_3 175-177           Q097_A 178-180        
   Q097_B 181-183           Q097_C 184-186           Q098 187              
   Q099 188-189             Q100 190-191             Q101 192-193          
   Q102 194-195             Q103 196-197             Q104 198              
   Q105 199                 Q106 200                 Q107 201              
   Q108 202                 Q109 203                 Q110 204              
   Q111 205                 Q112 206                 Q113 207              
   Q114 208                 Q115 209                 Q116 210              
   Q116E 211                Q116C 212                Q117 213              
   Q118 214                 Q119 215                 Q120 216              
   Q121 217                 Q122 218                 Q123 219              
   Q124 220                 Q125 221                 Q126 222              
   Q127 223                 Q128 224                 Q129 225              
   Q130 226                 Q131 227                 Q132 228              
   Q133 229                 Q134 230                 Q135 231              
   Q136 232                 Q137 233                 Q138 234              
   Q139 235                 Q140 236                 Q141 237              
   Q142 238                 Q143 239                 Q144 240              
   Q145 241                 Q146 242                 Q147 243              
   Q148 244                 IR001 245-246            IR002 247             
   IR002A 248               IR002B 249-250           IR002C 251            
   IR003 252                IR003A 253               IR004 254             
   IR005 255                IR006 256                IR007_1 257           
   IR007_2 258              IR007_3 259              IR008 260             
   IR009 261                IR010A 262               IR010B 263            
   IR010C 264               IR010D 265               IR010E 266            
   MN001 267                EDWEIGHT 268-272         SWEIGHT 273-281       
   W_MO 282-297 .        


FORMATS
  SE005A (F5.1) /          EDWEIGHT (F6.4) /        SWEIGHT (F10.7) /      
  W_MO (F17.15) / .
    
VARIABLE LABELS
   COUNTRY 'country code'
   IDNUMBER 'ID number'
   LEVEL1 'Area'
   LEVEL3 'rural-urban'
   YRSURVEY 'Survey year'
   SE002 'gender'
   SE003 'age'
   SE003A 'Actual Age'
   SE004 'marital status'
   SE004A 'Marital Status(Y/N)'
   SE005 'education'
   SE005A 'How many years of formal education you have received?'
   SE005B 'education(four categories)'
   SE005C 'education(original)'
   SE006 'What is your religious belief?'
   SE006A 'What is your religious belief?(original)'
   SE007 'How often do you practice religious service these days?'
   SE008A 'size of the household'
   SE008B 'How many people live in the hosehold?'
   SE009 'monthly household income(five categories)'
   SE009D 'annual income: urban and rural quintiles calculated separately'
   SE009B 'monthly household income(nine categories)'
   SE009A 'source of income'
   SE009A_1 'source of income_1'
   SE009A_2 'source of income_2'
   SE009A_3 'source of income_3'
   SE012A 'main occupation'
   SE012BMO 'employment'
   SE014 'What language do you speak the most in the home?'
   SE016 "Where is the place of your father's origin?"
   SE016A 'Subjective Ethnic identity'
   SE017 'Subjective Social status'
   RELIG1 'Religion'
   FGNUM 'Formal group number'
   PGNUM 'Private group number'
   Q001 'current economic condition of our country'
   Q002 "country's current economic condition compared with 5 years ago"
   Q003 'future economic change of our country compared with present'
   Q004 "your family's current economic condition"
   Q005 "your family's current economic condition compared with 5 years" +
   " ago"
   Q006 "your family's future economic condition compared with present"
   Q007 'how much trust in courts?'
   Q008 'how much trust in national government?'
   Q009 'how much trust in political parties?'
   Q010 'how much trust in parliament?'
   Q011 'how much trust in civil service?'
   Q012 'how much trust in the military?'
   Q013 'how much trust in the police?'
   Q014 'how much trust in local government?'
   Q015 'how much trust in newspapers?'
   Q016 'how much trust in TV?'
   Q017 'how much trust in the election commission?'
   Q018 'how much trust in nongovernmental organizations?'
   Q018_6 'how much trust in radio?'
   Q019 'Are you a member of any organization or formal groups?'
   Q019_1 'Which organizations or formal groups do you belong to(1st)?'
   Q019_2 'Which organizations or formal groups do you belong to(2nd)?'
   Q019_3 'Which organizations or formal groups do you belong to(3rd)?'
   Q020 'Are you a member of any private groups, circles or regular' +
   ' gatherings?'
   Q020_1 'The name of private group, circle or regular gatherings(1st)'
   Q020_2 'The name of private group, circle or regular gatherings(2nd)'
   Q020_3 'The name of private group, circle or regular gatherings(3rd)'
   Q021 'which of these org-s or groups /Q19,20/ you just mentioned' +
   ' matters the most to you?'
   Q022 'How frequently do you participate?'
   Q023 'How often do you discuss politics?'
   Q024 'Can most people can be trusted??'
   Q025 'I have enough friends and connections so that I can get help if I' +
   ' need it'
   Q026 "I have some friends with influence, so I don't have to worry too" +
   " much if I get into a tight spot"
   Q027 'Have you participated in last election?'
   Q028 'Which party did you vote for?'
   Q029 'Did you attend a campaign meeting or rally?'
   Q030 'Did you try to persuade others to vote for a certain candidate or' +
   ' party?'
   Q031 'Did you do anything else to help or show your support for a party' +
   ' or candidate running in the election?'
   Q032 'Asked you to vote for a particular candidate?_FAMILY' +
   ' MEMBER/RELATIVE'
   Q033 'Asked you to vote for a particular candidate?_SENIORS IN A CLAN' +
   ' OR EXTENDED FAMILY'
   Q034 'Asked you to vote for a particular candidate?_NEIGHBOR/FRIEND'
   Q035 'Asked you to vote for a particular candidate?_COMMUNITY LEADERS'
   Q036 'Asked you to vote for a particular candidate?_SUPERIOR AT' +
   ' WORK/SCHOOL'
   Q037 'Asked you to vote for a particular candidate?_OWNERS OF THE' +
   ' FIRM/UNIT THAT YOU WORK FOR'
   Q038 'Asked you to vote for a particularcandidate?_MEMBER/OFFICIAL OF' +
   ' ORGANIZATION THAT YOU BELONG TO'
   Q039 'Asked you to vote for a particular candidate?_GOVERNMENT OFFICIAL' +
   ' WHOM YOU KNOW PERSONALLY'
   Q040 "Asked you to vote for a particular candidate?_GOVERNMENT OFFICIAL" +
   " WHOM YOU DON'T KNOW"
   Q041 'Asked you to vote for a particular candidate?_CANDIDATE/PARTY' +
   ' ACTIVIST WHOM YOU KNOW PERSONALLY'
   Q042 'Asked you to vote for a particular candidate?_CANDIDATE/PARTY' +
   ' ACTIVIST WHOM YOU DONT KNOW'
   Q043 'Asked you to vote for a particular candidate?_OTHERS'
   Q044 'Influential_FAMILY MEMBER/RELATIVE'
   Q045 'Influential_SENIORS IN A CLAN OR EXTENDED FAMILY'
   Q046 'Influential_NEIGHBOR/FRIEND'
   Q047 'Influential_COMMUNITY LEADERS'
   Q048 'Influential_SUPERIOR AT WORK/SCHOOL'
   Q049 'Influential_OWNERS OF THE FIRM/UNIT THAT YOU WORK FOR'
   Q050 'Influential_MEMBER/OFFICIAL OF ORGANIZATION THAT YOU BELONG TO'
   Q051 'Influential_GOVERNMENT OFFICIAL WHOM YOU KNOW PERSONALLY'
   Q052 "Influential_GOVERNMENT OFFICIAL WHOM YOU DON'T KNOW"
   Q053 'Influential_CANDIDATE/PARTY ACTIVIST WHOM YOU KNOW PERSONALLY'
   Q054 "Influential_CANDIDATE/PARTY ACTIVIST WHOM YOU DON'T KNOW"
   Q055 'Influential_OTHERS'
   Q056 'how interested would you say you are in politics?'
   Q057 'how often do you follow news about politics?'
   Q058 'how often do you follow news about politics in the daily' +
   ' newspaper?'
   Q059 'how often do you follow politics in the news on TV?'
   Q060 'how often do you follow politics in the news on the radio?'
   Q061 'how much impact do you feel gov. policies have on your daily' +
   ' life?'
   Q062 'which party if any do you feel closest to?'
   Q063 'how close do you feel?'
   Q064 "Even if parents' demands are unreasonable, children still should" +
   " do what they ask?"
   Q065 'When hiring someone, even if a stranger is more qualified, the' +
   ' opportunity should still be given to relatives and friend'
   Q066 'When one has a conflict with a neighbor, the best way to deal' +
   ' with it is to accommodate the other person?'
   Q067 'Wealth and poverty, success and failure are all determined by' +
   ' fate?'
   Q068 'A person should not insist on his own opinion if his co-workers' +
   ' disagree with him?'
   Q069 'For the sake of the family, the individual should put his' +
   ' personal interests second?'
   Q070 'A man will lose face if he works under a female supervisor?'
   Q071 'If there is a quarrel, we should ask an elder to resolve the' +
   ' dispute?'
   Q072 'When a mother-in-law and a daughter-in-law come into conflict,' +
   ' even if the mother-in-law is in the wrong, the husband sh'
   Q073 'Contacted any government official to express your opinions?'
   Q074 'Contacted officials to express your opinions at higher level?'
   Q075 'contacted elected legislative representatives at any level?'
   Q076 'Contacted political parties or other political organizations?'
   Q077 'Contacted non-government/civil society organizations?'
   Q078 'Contacted media to comment on something?'
   Q079 'Demonstrated, striken, or sat-in for something?'
   Q080 'Contacted other people?'
   Q081 'Did you do this alone or with others?_contacted government' +
   ' official'
   Q082 'Did you do this alone or with others?_contacted officials at' +
   ' higher level'
   Q083 'Did you do this alone or with others?_contacted elected' +
   ' legislative representatives at any level'
   Q084 'Did you do this alone or with others?_contacted political parties' +
   ' or other political organizations'
   Q085 'Did you do this alone or with others?_contacted no' +
   'n-government/civil society organizaions'
   Q086 'Did you do this alone or with others?_contacted media'
   Q087 'Did you do this alone or with others?_demonstration, strike,' +
   ' sit-in'
   Q088 'Did you do this alone or with others?_contacted other people'
   Q089 'Gift or dinner_contacted government'
   Q090 'Gift or dinner_contacted officials at highter level'
   Q091 'Gift or dinner_contacted elected legislative representatives'
   Q092 'Gift or dinner_contacted political parties or other political' +
   ' organizations'
   Q093 'Gift or dinner_contacted non-goverment/civil society' +
   ' organizations'
   Q094 'Gift or dinner_contacted media'
   Q095 'Gift or dinner_demonstration, strike, sit-in'
   Q096 'Gift or dinner_contacted other people'
   Q097_1 'what does democracy mean?(The first answer)'
   Q097_2 'what does democracy mean?(The second answer)'
   Q097_3 'what does democracy mean?(The third answer)'
   Q097_A 'what does democracy mean?(The first answer)'
   Q097_B 'what does democracy mean?(The second answer)'
   Q097_C 'what does democracy mean?(The third answer)'
   Q098 'Satisfaction with the way democracy works in our country?'
   Q099 'Where would you place our country before 1990?'
   Q100 'Where would you place our country under the present government?'
   Q101 'To what extent would you want our country to be democratic now?'
   Q102 'Where do you expect our country to be in five years?'
   Q103 'Do you think democracy is suitable for our country?'
   Q104 'How satisfied or dissatisfied are you with the Enkhbayar govt?'
   Q105 'Everyone is free to say what they think- is better than old' +
   ' regime?'
   Q106 'Everyone is treated equally by the government- is better than old' +
   ' regime?'
   Q107 'People like me can have an influence on government- is better' +
   ' than old regime?'
   Q108 'Corruption in politics and government is under control- is better' +
   ' than old regime?'
   Q109 'The gap between the rich and the poor have narrowed- is better' +
   ' than old regime?'
   Q110 'Preventing crime and maintaining order- is better than old' +
   ' regime?'
   Q111 'Economic development- is better than old regime?'
   Q112 'Judges and courts are free from political interference- is better' +
   ' than old regime?'
   Q113 'You can join any organization you like- is better than old' +
   ' regime?'
   Q114 'How widespread corruption in your local/municipal government?'
   Q115 'How widespread corruption in the national government?'
   Q116 'Have you or anyone you know personally witnessed an act of' +
   ' corruption or bribe-taking by a politician or government offi'
   Q116E 'anyone you know personally witnessed '
   Q116C 'anyone you know personally witnessed an act of corruption?'
   Q117 'Which comes closest to your own opinion?'
   Q118 'Which comes closer to your own view?'
   Q119 'choose between democracy and economic development?'
   Q120 'Which comes closer to your own view?'
   Q121 'We should get rid of parliament and elections and have a strong' +
   ' leader decide things'
   Q122 'No opposition party should be allowed to compete for power'
   Q123 'The military should come in to govern the country'
   Q124 'We should get rid of parliament and elections and have the' +
   ' experts decide everything'
   Q125 'It is ok for the government to disregard the law in order to deal' +
   ' with the situation, when the country is facing a diffi'
   Q126 'I have the ability to participate in politics'
   Q127 "Politics and government seems so complicated that a person like" +
   " me can't really understand what is going on"
   Q128 'The nation is run by a powerful few and ordinary citizens cannot' +
   ' do much about it'
   Q129 "People like me don't have any influence over what the government" +
   " does"
   Q130 'Our form of government is still the best for us'
   Q131 'You can generally trust the people who run our government to do' +
   ' what is right'
   Q132 'People with little or no education should have as much say in' +
   ' politics as highly-educated people'
   Q133 'Government leaders are like the head of a family; we should all' +
   ' follow their decisions'
   Q134 'The government should decide whether certain ideas should be' +
   ' allowed to be discussed in society'
   Q135 'Harmony of the community will be disrupted if people organize' +
   ' lots of groups'
   Q136 'When judges decide important cases, they should accept the view' +
   ' of the executive branch'
   Q137 'If the government is constantly checked by the legislature, it' +
   ' cannot possibly accomplish great things'
   Q138 'If we have political leaders who are morally upright, we can let' +
   ' them decide everything'
   Q139 'If people have too many different ways of thinking, society will' +
   ' be chaotic'
   Q140 'The government should maintain ownership of major state-owned' +
   ' enterprises'
   Q141 'The national government should have more authority over local' +
   ' decisions than it does now'
   Q142 'Our country should defend our way of life instead of becoming' +
   ' more and more like other countries'
   Q143 'For the sake of the national community/society, the individual' +
   ' should be prepared to sacrifice his personal interest'
   Q144 'The state is like a big machine and the individual is but a small' +
   ' cog, with no independent status'
   Q145 'The most important thing for a political leader is to accomplish' +
   ' his goals even if he has to ignore the established proc'
   Q146 'If a political leader really believes in his position, he should' +
   ' refuse to compromise regardless of how many people disa'
   Q147 'A political leader should tolerate the views of those who' +
   ' challenge his political ideals'
   Q148 'As long as a political leader enjoys majority support, he should' +
   ' implement his own agenda and disregard the view of the '
   IR001 'Interviewer_s number'
   IR002 'Is this the first questionnaire the interviewer have completed?'
   IR002A 'Interviewer_s gender'
   IR002B 'Interviewer_s age'
   IR002C 'What kind of language do you normally use at home'
   IR003 'Presence of others other than the respondent while' +
   ' interviewing
'
   IR003A 'Who were they?'
   IR004 'Has the respondent ever refused to be interviewed during the' +
   ' whole process?'
   IR005 'Has the respondent ever felt impatient during the interview?'
   IR006 'How cooperative was the respondent during the interview?'
   IR007_1 'date of interview: month'
   IR007_2 'date of interview: day'
   IR007_3 'date of interview: year'
   IR008 'Language in which interview was conducted'
   IR009 'Was the interview conducted with the assisance of an interpreter'
   IR010A "What is the condition of the road leading to interview's" +
   " residence"
   IR010B "How do rate the sanitary condition in the public area in the" +
   " interviewee's nearby neighborhood"
   IR010C "Tell us whetherthe interviewee's residence has public water" +
   " supply"
   IR010D "Tell us whetherthe interviewee's residence has electricity"
   IR010E "Walking distance between the nearest public transportation stop" +
   " and the respondent's house"
   MN001 'how much trust in radio?'
   EDWEIGHT 'edweight'
   SWEIGHT 'sweight'
   W_MO 'weight for sex, age, region' .

VALUE LABELS
 COUNTRY
     5 'Mongolia' /
 LEVEL1
     1 'UB'
     2 'tov'
     3 'ovorhangai'
     4 'hovsgol'
     5 'hovd'
     6 'dornod'
     7 'dundgovi'
     8 'darhan' /
 LEVEL3
     1 'urban'
     2 'rural' /
 YRSURVEY
     2003 '2003' /
 SE002
     1 'male'
     2 'female' /
 SE003
     1 '18-19'
     2 '20-24'
     3 '25-29'
     4 '30-34'
     5 '35-39'
     6 '40-44'
     7 '45-49'
     8 '50-54'
     9 '55-59'
     10 '60-70'
     11 '71-75'
     12 '76&over'
     99 'No Answer' /
 SE004
     1 'married'
     2 'living -in as married'
     3 'widowed'
     4 'married but separated'
     5 'divorsed'
     6 'single/never married'
     99 'No Answer' /
 SE004A
     1 'Yes'
     2 'No'
     99 'No Answer' /
 SE005
     1 'No formal'
     2 'Incomplete primary /elementary'
     3 'Complete primary /elementary'
     4 'Incomplete secondary/high'
     5 'Complete secondary/high'
     6 'Incomplete secondary/high school'
     7 'Complete secondary/high school'
     8 'Some university/college-level, with diploma'
     9 'With University/College degree'
     10 'Post-graduate degree/Associated degree'
     98 "Don't know"
     99 'No answer' /
 SE005A
     1 '1 year'
     2 '2 years'
     3 '3 years'
     4 '4years'
     5 '5 years'
     6 '6 years'
     7 '7 years'
     8 '8 years'
     9 '9 years'
     10 '10 years'
     12.5 '11-14 years'
     15.5 '15-16 years'
     17 '17&over years'
     99 'No Answer' /
 SE005B
     1 'illiterate'
     2 'primary education'
     3 'secondary education'
     4 'tertitary education'
     98 "Don't Know"
     99 'No Answer' /
 SE005C
     1 'no formal education'
     2 'complete primery education'
     3 'incomplete sec.educ'
     4 'complete sec.educ'
     5 'complete sec-technical/voc'
     6 'university-level educ, with diploma'
     7 'post-graduate degrees'
     99 'No Answer' /
 SE006
     1 'Shinto'
     2 'Daoism'
     3 'Other Folk Religio'
     4 'Born again'
     5 'Buddhism'
     6 'Hinduism'
     7 'Islam'
     8 'Roman Catholics'
     9 'Protestantism'
     10 'Others'
     11 'None'
     97 'Not applicable'
     99 'No Answer' /
 SE006A
     1 'roman catholic'
     2 'protestant'
     3 'islam'
     4 'buddhist'
     5 'none'
     6 'other'
     99 'No Answer' /
 SE007
     1 'several times a day'
     2 'once a day'
     3 'sev.times a week'
     4 'once a week'
     5 'once a month'
     6 'only on special rel.days'
     7 'once a year'
     8 'less often'
     9 'practically never'
     99 'No Answer' /
 SE008A
     1 '1 people'
     2 '2 people'
     3 '3 people'
     4 '4 people'
     5 '5 people'
     6 '6 people'
     7 '7 people'
     8 '8 people'
     9 '9 people'
     10 '10 people'
     11 'more than 10 people'
     99 'No Answer' /
 SE008B
     1 'one generation'
     2 '2 generations'
     3 '3 generations'
     4 'more than 3 generations'
     99 'No Answer' /
 SE009
     1 '18000-38000 Tugrik'
     2 '38001-58000 Tugrik'
     3 '58001-78000 Tugrik'
     4 '78001-98000 Tugrik'
     5 'more than 98000 Tugrik'
     99 'No Answer' /
 SE009B
     1 '18000-28000 Tugrik'
     2 '28001-38000 Tugrik'
     3 '38001-48000 Tugrik'
     4 '48001-58000 Tugrik'
     5 '58001-68000 Tugrik'
     6 '68001-78000 Tugrik'
     7 '78001-88000 Tugrik'
     8 '88001-98000 Tugrik'
     9 'more than 98000 Tugrik'
     99 'No Answer' /
 SE009A
     1 'wages&salaries'
     2 'rentals of property or any asset'
     3 'business inc'
     4 'gift, help from relatives amd other people'
     5 'pension& retirement benefits'
     6 'pension, '
     7 'corruption'
     8 'other'
     99 'No Answer' /
 SE009A_1
     1 'wages&salaries'
     2 'rentals of property or any asset'
     3 'business inc'
     4 'gift, help from relatives amd other people'
     5 'pension& retirement benefits'
     6 'pension, '
     7 'corruption'
     8 'other'
     99 'No Answer' /
 SE009A_2
     1 'wages&salaries'
     2 'rentals of property or any asset'
     3 'business inc'
     4 'gift, help from relatives amd other people'
     5 'pension& retirement benefits'
     6 'pension, '
     7 'corruption'
     8 'other'
     99 'No Answer' /
 SE009A_3
     1 'wages&salaries'
     2 'rentals of property or any asset'
     3 'business inc'
     4 'gift, help from relatives amd other people'
     5 'pension& retirement benefits'
     6 'pension, '
     7 'corruption'
     8 'other'
     99 'No Answer' /
 SE012A
     1 'Admin/Manager'
     2 'Professional'
     3 'Clerical'
     4 'Sale'
     5 'Service'
     6 'Farmer'
     7 'Manual worker'
     8 'Not working'
     9 'Other'
     97 'Not Applicable'
     98 "Don't know"
     99 'No Answer' /
 SE012BMO
     1 'wage worker'
     2 'members of armed forces, sec.personnel'
     3 'manager'
     4 'office worker'
     5 'employer'
     6 'worker, has a private sector'
     7 'lessor'
     8 'unemployed, /not looking for a job/'
     9 'unemp, /looking for a job/'
     10 'pensioner'
     11 'person, who has got a aid'
     13 'student'
     99 'No Answer' /
 SE014
     1 'Mongolian'
     2 'Russian'
     3 'English'
     4 'other'
     99 'No Answer' /
 SE016
     99 'No Answer'
     501 'Halh'
     502 'Hasag'
     503 'Buriad'
     504 'Dorvod'
     505 'Bayad'
     506 'Hoton'
     507 'Zahchin'
     508 'Mingad'
     509 'torguud'
     510 'Urianhai'
     511 'Darhad'
     512 'Dariganga'
     513 'Uzemchin'
     514 'Oold'
     515 'Barga'
     516 'China'
     517 'Russia'
     518 'Uzbek' /
 SE017
     1 'upper class'
     2 'upper middle'
     3 'middle'
     4 ' lower middle'
     5 'lower '
     97 "don't know"
     98 'none of these'
     99 'no answer' /
 RELIG1
     5 'Buddhism'
     7 'Islam'
     8 'Roman Catholics'
     9 'Protestantism'
     10 'Others'
     11 'None'
     97 'Not Applicable' /
 FGNUM
     0 'None'
     1 'One'
     2 'Two'
     3 'Three' /
 PGNUM
     0 'None'
     1 'One'
     2 'Two'
     3 'Three' /
 Q001
     1 'very bad'
     2 'bad'
     3 'so so'
     4 'good'
     5 'very good'
     99 'No Answer' /
 Q002
     1 'much worse'
     2 'little worse'
     3 'same'
     4 'little bet'
     5 'much better'
     99 'No Answer' /
 Q003
     1 'much worse'
     2 'little worse'
     3 'same'
     4 'little bet'
     5 'much better'
     99 'No Answer' /
 Q004
     1 'very bad'
     2 'bad'
     3 'so so'
     4 'good'
     5 'very good' /
 Q005
     1 'much worse'
     2 'little worse'
     3 'same'
     4 'little bet'
     5 'much better'
     99 'No Answer' /
 Q006
     1 'much worse'
     2 'little worse'
     3 'same'
     4 'little bet'
     5 'much better'
     99 'No Answer' /
 Q007
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q008
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q009
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q010
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q011
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q012
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q013
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q014
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q015
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust' /
 Q016
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q017
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q018
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q018_6
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No answer' /
 Q019
     2 'residantial ass'
     3 'parent-teacher ass'
     4 'trade ass'
     5 'agricult.org'
     6 'labor union'
     7 'producer cooperative'
     8 'consumer cooperative'
     9 'volunteer group'
     10 'citizen movement org'
     11 'religious group'
     12 'alumny ass'
     13 'candidate support org'
     14 'pol.party'
     15 'sports or leisure club'
     99 'not a member of any org' /
 Q019_1
     2 'residantial ass'
     3 'parent-teacher ass'
     4 'trade ass'
     5 'agricult.org'
     6 'labor union'
     7 'producer cooperative'
     8 'consumer cooperative'
     9 'volunteer group'
     10 'citizen movement org'
     11 'religious group'
     12 'alumny ass'
     13 'candidate support org'
     14 'pol.party'
     15 'sports or leisure club'
     99 'not a member of any org' /
 Q019_2
     2 'residantial ass'
     3 'parent-teacher ass'
     4 'trade ass'
     5 'agricult.org'
     6 'labor union'
     7 'producer cooperative'
     8 'consumer cooperative'
     9 'volunteer group'
     10 'citizen movement org'
     11 'religious group'
     12 'alumny ass'
     13 'candidate support org'
     14 'pol.party'
     15 'sports or leisure club'
     97 'No Application'
     99 'not a member of any org' /
 Q019_3
     2 'residantial ass'
     3 'parent-teacher ass'
     4 'trade ass'
     5 'agricult.org'
     6 'labor union'
     7 'producer cooperative'
     8 'consumer cooperative'
     9 'volunteer group'
     10 'citizen movement org'
     11 'religious group'
     12 'alumny ass'
     13 'candidate support org'
     14 'pol.party'
     15 'sports or leisure club'
     97 'No Application'
     99 'not a member of any org' /
 Q020
     2 'circle of colleagues who interact out of work'
     3 'group at community schools or other place of learning'
     4 'group of common hobbies'
     5 'business group'
     6 'circle of friends who exchange information'
     7 'informal credit/loan assoc'
     99 'not a member' /
 Q020_1
     2 'circle of colleagues who interact out of work'
     3 'group at community schools or other place of learning'
     4 'group of common hobbies'
     5 'business group'
     6 'circle of friends who exchange information'
     7 'informal credit/loan assoc'
     97 'No Application'
     99 'not a member' /
 Q020_2
     2 'circle of colleagues who interact out of work'
     3 'group at community schools or other place of learning'
     4 'group of common hobbies'
     5 'business group'
     6 'circle of friends who exchange information'
     7 'informal credit/loan assoc'
     97 'No Application'
     99 'not a member' /
 Q020_3
     2 'circle of colleagues who interact out of work'
     3 'group at community schools or other place of learning'
     4 'group of common hobbies'
     5 'business group'
     6 'circle of friends who exchange information'
     7 'informal credit/loan assoc'
     97 'No Application'
     99 'not a member' /
 Q021
     2 'resid.ass'
     3 'parent teach'
     4 'trade ass'
     5 'agri.ass'
     6 'labor union'
     7 'producer coop'
     8 'consumer coop'
     9 'volunt'
     10 'citiz'
     11 'relig.group'
     12 'alumny'
     13 'cand.support'
     14 'pol.party'
     15 'sports club'
     16 'circle out of work'
     17 'community schools'
     18 'circle of friends'
     19 'business circle'
     20 'information circle'
     21 'informal credit'
     99 'No Answer' /
 Q022
     1 'never'
     2 'rarely'
     3 'sometimes'
     4 'often'
     5 'very often'
     99 'No Answer' /
 Q023
     1 'never'
     2 'rarely'
     3 'sometimes'
     4 'often'
     5 'very often'
     99 'No Answer' /
 Q024
     1 "one can't be too careful in dealing with them"
     2 'most people can be trusted'
     99 'No Answer' /
 Q025
     1 'appies ver.well'
     2 'app pretty well'
     3 "doesn't app.much"
     4 "doesn't app at all"
     99 'No Answer' /
 Q026
     1 'app.ver. well'
     2 'app.pretty well'
     3 "doesn't app much"
     4 "doesn't app.at all"
     99 'No Answer' /
 Q027
     1 'no'
     2 'yes'
     97 'not applicable'
     98 "don't rem"
     99 'No Answer' /
 Q028
     99 'No Answer'
     501 'MAHN'
     502 'AN'
     503 'MAShSN'
     504 'IZ-BNN'
     505 'other' /
 Q029
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q030
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q031
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q032
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q033
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q034
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q035
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q036
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q037
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q038
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q039
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q040
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q041
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q042
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q043
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q044
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q045
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q046
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q047
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q048
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q049
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q050
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q051
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q052
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q053
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q054
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q055
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'no answer' /
 Q056
     1 'not at all int'
     2 'not very int'
     3 'somewhat int'
     4 'very intereted'
     98 "don't khow" /
 Q057
     2 'practically never'
     3 'not even once a week'
     4 'once or twice a wek'
     5 'several times a week'
     6 'everyday' /
 Q058
     2 'practically never'
     3 'not even once a week'
     4 'once or twice a wek'
     5 'several times a week'
     6 'everyday' /
 Q059
     2 'practically never'
     3 'not even once a week'
     4 'once or twice a wek'
     5 'several times a week'
     6 'everyday'
     99 'No Answer' /
 Q060
     2 'practically never'
     3 'not even once a week'
     4 'once or twice a wek'
     5 'several times a week'
     6 'everyday'
     99 'No Answer' /
 Q061
     1 'no impact at all'
     2 'a little impact'
     3 'quite some impact'
     4 'a great deal of impact'
     99 'No Answer' /
 Q062
     99 'Do not feel close'
     501 'MAHN'
     502 'AN'
     503 'IZ-BNN'
     504 'MASnSN'
     505 'others' /
 Q063
     1 'just a little close'
     2 'somewhat close'
     3 'very close'
     99 'No Answer' /
 Q064
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD' /
 Q065
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q066
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD' /
 Q067
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q068
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q069
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q070
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q071
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD' /
 Q072
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q073
     1 'once'
     2 'more then once'
     9 'never done' /
 Q074
     1 'once'
     2 'more then once'
     9 'never done' /
 Q075
     1 'once'
     2 'more then once'
     9 'never done' /
 Q076
     1 'once'
     2 'more then once'
     9 'never done' /
 Q077
     1 'once'
     2 'more then once'
     9 'never done' /
 Q078
     1 'once'
     2 'more then once'
     9 'never done' /
 Q079
     1 'once'
     2 'more then once'
     9 'never done' /
 Q080
     1 'once'
     2 'more then once'
     9 'never done' /
 Q081
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q082
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q083
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q084
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q085
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q086
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q087
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q088
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q089
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q090
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q091
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q092
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q093
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q094
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q095
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q096
     1 'no'
     2 'yes'
     97 'Not applicable'
     99 'No Answer' /
 Q097_1
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_2
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_3
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_A
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_B
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_C
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q098
     1 'not at all sat'
     2 'not very sat'
     3 'fairly sat'
     4 'very satisfied'
     99 'No Answer' /
 Q099
     1 'complete dictatorship'
     10 'complete democracy'
     98 "Don't Know" /
 Q100
     1 'complete dictatorship'
     10 'complete democracy'
     98 "Don't Know" /
 Q101
     1 'complete dictatorship'
     10 'complete democracy'
     98 "Don't Know" /
 Q102
     1 'complete dictatorship'
     10 'complete democracy'
     98 "Don't Know" /
 Q103
     1 'democracy is completely unsuitable'
     10 'democracy is perfectly suitable'
     98 "Don't Know" /
 Q104
     1 'Very disatisfied'
     2 'Somewhat dissatisfied'
     3 'Somewhat satisfied'
     4 'very satisfied'
     99 'No Answer' /
 Q105
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q106
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q107
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q108
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q109
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q110
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q111
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q112
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q113
     1 'much worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better then before'
     99 'No Answer' /
 Q114
     1 'almost everyone is corrupt'
     2 'most off-s are corrupt'
     3 'not a lot of officials are corrupt'
     4 'hardly anyone is involved'
     99 'No Answer' /
 Q115
     1 'almost everyone is corrupt'
     2 'most off-s are corrupt'
     3 'not a lot of officials are corrupt'
     4 'hardly anyone is involved'
     99 'No Answer' /
 Q116
     1 'Yes'
     2 'No'
     98 "Don't know"
     99 'No answer' /
 Q116E
     1 'Personally'
     2 'Family member'
     3 'Friend'
     4 'None'
     99 'No Answer' /
 Q116C
     1 'witnessed'
     2 'personally witnessed'
     3 'told about it by a fam.mem  who pers.witnessed'
     4 'told about it by friend '
     5 'personally never witnessed'
     6 'no one I know has personally witnessed'
     99 'No Answer' /
 Q117
     1 'an authoritarian government can be preferable to dem once'
     2 "it doesn't matter whether we have dem or non dem regime"
     3 'democracy is better than other kind of gov'
     99 'No Answer' /
 Q118
     1 "democracy can't solve our problems"
     2 'democracy is capable of solving our problems'
     99 'No Answer' /
 Q119
     1 'economic devlopment is definitely more imp-t'
     2 'economic devlopment  is somewhat more imp-t'
     3 'democracy is somewhat more important'
     4 'democracy is definitely more important'
     5 'they are both equally important'
     99 'No Answer' /
 Q120
     1 'it is essantial that the remains one nation'
     2 'parts of the country should be allowed...'
     3 "can't choose"
     99 'No Answer' /
 Q121
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q122
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q123
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q124
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q125
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q126
     1 'SD'
     2 'SWD'
     3 'SWA'
     4 'SA'
     99 'No Answer' /
 Q127
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q128
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q129
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q130
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q131
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q132
     1 'SD'
     2 'SWD'
     3 'SWA'
     4 'SA'
     99 'No Answer' /
 Q133
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q134
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q135
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q136
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q137
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q138
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q139
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q140
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q141
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q142
     1 'SD'
     2 'SWD'
     3 'SWA'
     4 'SA'
     99 'No Answer' /
 Q143
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q144
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q145
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q146
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 Q147
     1 'SD'
     2 'SWD'
     3 'SWA'
     4 'SA'
     99 'No Answer' /
 Q148
     1 'SA'
     2 'SWA'
     3 'SWD'
     4 'SD'
     99 'No Answer' /
 IR002
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR002A
     1 'Male'
     2 'Female'
     99 'No Answer' /
 IR002B
     18 '18'
     19 '19'
     20 '20'
     22 '22'
     23 '23'
     24 '24'
     25 '25'
     26 '26'
     27 '27'
     28 '28'
     29 '29'
     30 '30'
     33 '33'
     34 '34'
     35 '35'
     36 '36'
     40 '40'
     41 '41'
     43 '43'
     45 '45'
     47 '47'
     54 '54'
     55 '55'
     57 '57'
     99 'No Answer' /
 IR002C
     99 'No Answer' /
 IR003
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR003A
     1 "resp's husbad"
     2 'children'
     3 'parents or parents-in-law'
     4 'relatives'
     5 'neighbours'
     6 'other'
     99 'No Answer' /
 IR004
     1 'yes, at the beginning'
     2 'yes, in the middle'
     3 'yes, by the end'
     4 'never'
     99 'No Answer' /
 IR005
     1 'never'
     2 'occasionally'
     3 'sometimes'
     4 'always'
     99 'No Answer' /
 IR006
     1 'highly coop'
     2 'fairly coop'
     3 'not very coop'
     99 'No Answer' /
 IR010A
     1 ' WIDE ENOUGH FOR CAR AND PAVED WITH ASPHALT,CEMENT OR MAN-MA'
     2 ' NOT WIDE ENOUGH FOR CAR BUT PAVED WITH ASPHALT,CEMENT OR MA'
     3 'Paved with stone'
     4 ' WIDE ENOUGH FOR CAR AND PAVED WITH STONE'
     5 ' NOT WIDE ENOUGH FOR CAR,BUT PAVED WITH STONE'
     6 'Unpaved/dirt road'
     7 ' WIDE ENOUGH FOR CAR AND UNPAVED/DIRT ROAD'
     8 ' NOT WIDE ENOUGHT FOR CAR BUT UNPAVED/DIRT ROAD'
     9 '.Muddy'
     10 ' WIDE ENOUGH FOR CAR AND MUDDY'
     11 ' NOT WIDE ENOUGH FOR CAR,BUT MUDDY'
     99 'No Answer' /
 IR010B
     1 'very bad'
     2 'somewhat bad'
     3 'so so'
     4 'fairly good'
     5 'good'
     99 'No Answer' /
 IR010C
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR010D
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR010E
     1 'Less than 10 minutes by walking'
     2 'Less than 20 minutes'
     3 'Less 40 minutes'
     4 'Less than an hour'
     5 'Less than 2 hours'
     6 'Less than 3 hours'
     7 'Less than 4 hours'
     8 'More than 4 hours'
     99 'No Answer' /
 MN001
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No answer' / .

/* User Missing Value Specifications */
MISSING VALUES
  SE003 (99)               SE004 (99)               SE004A (99)            
  SE005 (99)               SE005A (99)              SE005B (99)            
  SE005C (99)              SE006 (99)               SE006A (99)            
  SE007 (99)               SE008A (99)              SE008B (99)            
  SE009 (99)               SE009B (99)              SE009A (99)            
  SE009A_1 (99)            SE009A_2 (99)            SE009A_3 (99)          
  SE012A (97, 98, 99)      SE012BMO (99)            SE014 (99)             
  SE016 (99)               SE017 (97, 98, 99)       RELIG1 (97)            
  Q001 (99)                Q002 (99)                Q003 (99)              
  Q005 (99)                Q006 (99)                Q007 (99)              
  Q008 (99)                Q009 (99)                Q010 (99)              
  Q011 (99)                Q012 (99)                Q013 (99)              
  Q014 (99)                Q016 (99)                Q017 (99)              
  Q018 (99)                Q018_6 (99)              Q019_2 (97)            
  Q019_3 (97)              Q020_1 (97)              Q020_2 (97)            
  Q020_3 (97)              Q021 (99)                Q022 (99)              
  Q023 (99)                Q024 (99)                Q025 (99)              
  Q026 (99)                Q027 (97, 98, 99)        Q028 (99)              
  Q029 (97, 99)            Q030 (97, 99)            Q031 (97, 99)          
  Q032 (97, 99)            Q033 (97, 99)            Q034 (97, 99)          
  Q035 (97, 99)            Q036 (97, 99)            Q037 (97, 99)          
  Q038 (97, 99)            Q039 (97, 99)            Q040 (97, 99)          
  Q041 (97, 99)            Q042 (97, 99)            Q043 (97, 99)          
  Q044 (97, 99)            Q045 (97, 99)            Q046 (97, 99)          
  Q047 (97, 99)            Q048 (97, 99)            Q049 (97, 99)          
  Q050 (97, 99)            Q051 (97, 99)            Q052 (97, 99)          
  Q053 (97, 99)            Q054 (97, 99)            Q055 (97, 99)          
  Q056 (98)                Q059 (99)                Q060 (99)              
  Q061 (99)                Q062 (99)                Q063 (99)              
  Q065 (99)                Q067 (99)                Q068 (99)              
  Q069 (99)                Q070 (99)                Q072 (99)              
  Q081 (97, 99)            Q082 (97, 99)            Q083 (97, 99)          
  Q084 (97, 99)            Q085 (97, 99)            Q086 (97, 99)          
  Q087 (97, 99)            Q088 (97, 99)            Q089 (97, 99)          
  Q090 (97, 99)            Q091 (97, 99)            Q092 (97, 99)          
  Q093 (97, 99)            Q094 (97, 99)            Q095 (97, 99)          
  Q096 (97, 99)            Q097_1 (97, 98, 99)      Q097_2 (97, 98, 99)    
  Q097_3 (97, 98, 99)      Q097_A (97, 98, 99)      Q097_B (97, 98, 99)    
  Q097_C (97, 98, 99)      Q098 (99)                Q099 (98)              
  Q100 (98)                Q101 (98)                Q102 (98)              
  Q103 (98)                Q104 (99)                Q105 (99)              
  Q106 (99)                Q107 (99)                Q108 (99)              
  Q109 (99)                Q110 (99)                Q111 (99)              
  Q112 (99)                Q113 (99)                Q114 (99)              
  Q115 (99)                Q116 (99)                Q116E (99)             
  Q116C (99)               Q117 (99)                Q118 (99)              
  Q119 (99)                Q120 (99)                Q121 (99)              
  Q122 (99)                Q123 (99)                Q124 (99)              
  Q125 (99)                Q126 (99)                Q127 (99)              
  Q128 (99)                Q129 (99)                Q130 (99)              
  Q131 (99)                Q132 (99)                Q133 (99)              
  Q134 (99)                Q135 (99)                Q136 (99)              
  Q137 (99)                Q138 (99)                Q139 (99)              
  Q140 (99)                Q141 (99)                Q142 (99)              
  Q143 (99)                Q144 (99)                Q145 (99)              
  Q146 (99)                Q147 (99)                Q148 (99)              
  IR002 (99)               IR002A (99)              IR002B (99)            
  IR002C (99)              IR003 (99)               IR003A (99)            
  IR004 (99)               IR005 (99)               IR006 (99)             
  IR007_1 (99)             IR007_2 (99)             IR007_3 (9999)         
  IR010A (99)              IR010B (99)              IR010C (99)            
  IR010D (99)              IR010E (99)              MN001 (99) .
         

SAVE OUTFILE='.\mongolia v4.2.sav'.
