/* This SPSS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\thailand v4.2.dat" LRECL=351

DATA LIST FILE=DATA/
   COUNTRY 1                IDNUMBER 2-5             CHANGWAT 6-25 (A)     
   CHNO 26-27               AMPER 28-30              TAMBOL 31-33          
   MUBAN 34-36              REGION 37                LEVEL1 38             
   LEVEL3 39                LEVEL2_1 40              LEVEL2_2 41           
   LEVEL2_3 42              LEVEL3_1 43              LEVEL3_2 44           
   YRSURVEY 45-48           SE002 49                 SE003 50-51           
   SE003A 52-53             SE004 54                 SE004A 55             
   SE005 56-57              SE005A 58-60             SE005B 61             
   SE006 62-63              SE006A 64-65             SE007 66              
   SE008A 67-68             SE008B 69                SE009 70              
   SE009D 71                SE009A 72                SE012A 73             
   SE012BTH 74-75           SE012C 76-77             SE014 78              
   SE016 79                 SE016A 80                SE017 81              
   RELIG1 82-83             FGNUM 84                 PGNUM 85              
   Q001 86                  Q002 87                  Q003 88               
   Q004 89                  Q005 90                  Q006 91               
   Q007 92                  Q008 93                  Q009 94               
   Q010 95                  Q011 96                  Q012 97               
   Q013 98                  Q014 99                  Q015 100              
   Q016 101                 Q017 102                 Q018 103              
   Q018_7 104               Q018_8 105               Q018_9 106            
   Q019 107-108             Q019_2 109               Q019_3 110            
   Q019_4 111               Q019_5 112               Q019_6 113            
   Q019_7 114               Q019_8 115               Q019_9 116            
   Q019_10 117              Q019_11 118              Q019_12 119           
   Q019_13 120              Q019_14 121              Q019_15 122           
   Q019_16 123              Q020 124-125             Q020_2 126            
   Q020_3 127               Q020_4 128               Q020_5 129            
   Q020_6 130               Q020_7 131               Q020_8 132            
   Q021 133-137             Q022 138                 Q023 139              
   Q024 140                 Q025 141                 Q026 142              
   Q027 143                 Q028 144-146             Q029 147              
   Q030 148                 Q031 149                 Q032 150              
   Q033 151                 Q034 152                 Q035 153              
   Q036 154                 Q037 155                 Q038 156              
   Q039 157                 Q040 158                 Q041 159              
   Q042 160                 Q043 161                 Q044 162              
   Q045 163                 Q046 164                 Q047 165              
   Q048 166                 Q049 167                 Q050 168              
   Q051 169                 Q052 170                 Q053 171              
   Q054 172                 Q055 173                 Q056 174              
   Q057 175                 Q057A 176                Q058 177              
   Q059 178                 Q060 179                 Q061 180              
   Q062 181-183             Q063 184                 Q064 185              
   Q065 186                 Q066 187                 Q067 188              
   Q068 189                 Q069 190                 Q070 191              
   Q071 192                 Q072 193                 Q073 194              
   Q074 195                 Q075 196                 Q076 197              
   Q077 198                 Q078 199                 Q079 200              
   Q080 201                 Q081 202                 Q082 203              
   Q083 204                 Q084 205                 Q085 206              
   Q086 207                 Q087 208                 Q088 209              
   Q089 210                 Q090 211                 Q091 212              
   Q092 213                 Q093 214                 Q094 215              
   Q095 216                 Q096 217                 Q097_A 218            
   Q097_B 219               Q097_C 220               Q097_1 221-223        
   Q097_2 224-226           Q097_3 227-229           Q098 230              
   Q099 231-232             Q100 233-234             Q101 235-236          
   Q102 237-238             Q103 239-240             Q104 241              
   Q105 242                 Q106 243                 Q107 244              
   Q108 245                 Q109 246                 Q110 247              
   Q111 248                 Q112 249                 Q113 250              
   Q114 251                 Q115 252                 Q116 253              
   Q116E 254                Q116A 255-256            Q116B 257-258         
   Q117 259                 Q118 260                 Q119 261              
   Q120 262                 Q121 263                 Q122 264              
   Q123 265                 Q124 266                 Q125 267              
   Q126 268                 Q127 269                 Q128 270              
   Q129 271                 Q130 272                 Q131 273              
   Q132 274                 Q132A 275                Q133 276              
   Q134 277                 Q135 278                 Q136 279              
   Q137 280                 Q138 281                 Q139 282              
   Q140 283                 Q141 284                 Q142 285              
   Q143 286                 Q144 287                 Q145 288              
   Q146 289                 Q147 290                 Q148 291              
   IR001 292-294            IR002 295                IR002A 296            
   IR002B 297-298           IR002C 299               IR003 300             
   IR003A 301-302           IR004 303                IR005 304             
   IR006 305                IR007_1 306-307          IR007_2 308-309       
   IR007_3 310-313          IR008 314                IR009 315             
   IR010A 316               IR010B 317               IR010C 318            
   IR010D 319               IR010E 320               TH001 321-322         
   TH002 323-324            TH003 325                TH004 326             
   TH005 327                TH006 328                TH007 329             
   TH008 330                TH009 331                TH010 332             
   TH011 333                TH012 334                TH013 335             
   W_TH 336-351 .        


FORMATS
  SE005A (F4.1) /          Q021 (F6.2) /            W_TH (F17.15) / .
    
VARIABLE LABELS
   COUNTRY 'Code for Thailand'
   IDNUMBER 'ID number'
   CHANGWAT 'changwat name'
   CHNO 'changwat No.'
   AMPER 'amper No.'
   TAMBOL 'tumbon No.'
   MUBAN 'muban No.'
   REGION 'region'
   LEVEL1 'type of municipality'
   LEVEL3 'rural-urban: by subjective judgment of country expert'
   LEVEL2_1 'degree of urbanization: by official designation of administrative' +
   ' unit'
   LEVEL2_2 'degree of urbanization: by other criteria'
   LEVEL2_3 'degree of urbanization: by subjective judgment of country expert'
   LEVEL3_1 'rural urban: by other criteria'
   LEVEL3_2 'rural-urban: by subjective judgment of country expert'
   YRSURVEY 'survey year'
   SE002 'Gender'
   SE003 'Age'
   SE003A 'Actual Age'
   SE004 'Marital status'
   SE004A 'Marital Status(Y/N)'
   SE005 'Level of education'
   SE005A 'Years of education'
   SE005B 'Level of education(four categories)'
   SE006 'Religion'
   SE006A 'Religion(orignal)'
   SE007 'Frequency of religious activity'
   SE008A 'How many people live in this household'
   SE008B 'Size of extended family'
   SE009 'Income'
   SE009D 'annual income: urban and rural quintiles calculated separately'
   SE009A 'Sources of income'
   SE012A 'Main Occupation'
   SE012BTH 'Primary occupation of respondent'
   SE012C 'Occupation of primary income earner in home'
   SE014 'Language of the home'
   SE016 'Ethnicity'
   SE016A 'Subjective ethnicity identify'
   SE017 'Subjective social status'
   RELIG1 'Religion'
   FGNUM 'Formal group number'
   PGNUM 'Private group number'
   Q001 'How would you rate the overall economic condition'
   Q002 'How would you describe the change..over the 5 past years'
   Q003 'What do you think will be the state of our country 5 years from' +
   ' now'
   Q004 'As for your family, How do you rate your economic situation' +
   ' today'
   Q005 'How would you compare the current economic condition of your' +
   ' family with what it was 5 years ago'
   Q006 'What do you think the economic situation of your family will be 5' +
   ' years from now'
   Q007 'How much trust do you have in the courts?'
   Q008 'How much trust do you have in the national government?'
   Q009 'How much trust do you have in political parties?'
   Q010 'How much trust do you have in Parliament?'
   Q011 'How much trust do you have in civil service?'
   Q012 'How much trust do you have in the military?'
   Q013 'How much trust do you have in the police?'
   Q014 'How much trust do you have in local government?'
   Q015 'How much trust do you have in newspapers?'
   Q016 'How much trust do you have in television?'
   Q017 'How much trust do you have in the election commission?'
   Q018 'How much trust do you have in non-governmental organizations?'
   Q018_7 'Local MP(q18_1)'
   Q018_8 'The Constitution Court(q18_2)'
   Q018_9 'The Corruption Commission(q18_3)'
   Q019 'Are you a member of any organization or formal groups?
'
   Q019_2 'Residential association'
   Q019_3 'PTA'
   Q019_4 'Trade association'
   Q019_5 'Agricultural association'
   Q019_6 'Labor union'
   Q019_7 'Producer cooperative'
   Q019_8 'Consumer cooperative'
   Q019_9 'Volunteer group'
   Q019_10 'Citizen movement organization'
   Q019_11 'Religious group'
   Q019_12 'Alumni association'
   Q019_13 'Candidate support organization'
   Q019_14 'Political Party'
   Q019_15 'Sports or leisure club'
   Q019_16 'Other, Please specify'
   Q020 'Are you a member of any private groups, circles or regular' +
   ' gatherings?
'
   Q020_2 'Circle of colleagues who interact out of work'
   Q020_3 'Group at community schools'
   Q020_4 'Circle of friends who share common hobbies'
   Q020_5 'Circle of friends who do business'
   Q020_6 'Circle of friends who exchange information'
   Q020_7 'informal credit/loan association'
   Q020_8 'other, please specify'
   Q021 'Which of organization or groups you just mentioned matter the' +
   ' most for you'
   Q022 'How frequently do you participate in meeting and other activities' +
   ' of (answerQ21)'
   Q023 'How often do you discuss politics in (answer in Q21)'
   Q024 " "Most people can be trusted" or "you can't be careful in dealing" +
   " with them""
   Q025 'I have enough friends and connection so that I can get help if  I' +
   ' need it'
   Q026 "I have some friends with influence, so I don't have to worry if " +
   " I get into a tight spot"
   Q027 'Did you vote in the House of representative election'
   Q028 'Which party did you vote for'
   Q029 'Did you attend a campaign meeting or rally?'
   Q030 'Did you try to persuade others to vote for a certain candidate or' +
   ' party?'
   Q031 'Did you do anything else to help or show your support for a party' +
   ' or candidate running in the election?'
   Q032 'Asked to vote for a particular candidate?_FAMILY MEMBER/RELATIVE'
   Q033 'Asked following personally ask you to vote for a particular' +
   ' candidate?_SENIORS IN A CLAN OR EXTENDED FAMILY'
   Q034 'Asked to vote for a particular candidate?_NEIGHBOR/FRIEND'
   Q035 'Asked to vote for a particular candidate?_COMMUNITY LEADERS'
   Q036 'Asked to vote for a particular candidate?_SUPERIOR AT' +
   ' WORK/SCHOOL'
   Q037 'Asked to vote for a particular candidate?_OWNERS OF THE FIRM/UNIT' +
   ' THAT YOU WORK FOR'
   Q038 'Asked to vote for a particularcandidate?_MEMBER/OFFICIAL OF' +
   ' ORGANIZATION THAT YOU BELONG TO'
   Q039 'Asked to vote for a particular candidate?_GOVERNMENT OFFICIAL' +
   ' WHOM YOU KNOW PERSONALLY'
   Q040 "Asked to vote for a particular candidate?_GOVERNMENT OFFICIAL" +
   " WHOM YOU DON'T KNOW"
   Q041 'Asked to vote for a particular candidate?_CANDIDATE/PARTY' +
   ' ACTIVIST WHOM YOU KNOW PERSONALLY'
   Q042 'Asked to vote for a particular candidate?_CANDIDATE/PARTY' +
   ' ACTIVIST WHOM YOU DONT KNOW'
   Q043 'Asked to vote for a particular candidate?_OTHERS'
   Q044 'Influential_FAMILY MEMBER/RELATIVE'
   Q045 'Influential_SENIORS IN A CLAN OR EXTENDED FAMILY'
   Q046 'Influential_NEIGHBOR/FRIEND'
   Q047 'Influential_COMMUNITY LEADERS'
   Q048 'Influential_SUPERIOR AT WORK/SCHOOL'
   Q049 'Influential_OWNERS OF THE FIRM/UNIT THAT YOU WORK FOR'
   Q050 'Influential_MEMBER/OFFICIAL OF ORGANIZATION THAT YOU BELONG TO'
   Q051 'Influential_GOVERNMENT OFFICIAL WHOM YOU KNOW PERSONALLY'
   Q052 "Influential_GOVERNMENT OFFICIAL WHOM YOU DON'T KNOW"
   Q053 'Influential_CANDIDATE/PARTY ACTIVIST WHOM YOU KNOW PERSONALLY'
   Q054 "Influential_CANDIDATE/PARTY ACTIVIST WHOM YOU DON'T KNOW"
   Q055 'Influential_OTHERS'
   Q056 'How interested would you say you are in politics'
   Q057 'How often do you follow news about politics'
   Q058 'How often do you follow news about politics in the daily' +
   ' newspaper'
   Q059 'How often do you follow  politics in the news on TV'
   Q060 'How often do you follow  politics in the news on radio'
   Q061 'How much impact do you feel government policies have on your' +
   ' daily life'
   Q062 'Among the political parties, which party if any do you feel' +
   ' closest to'
   Q063 'How close do you feel to (answer in Q62)'
   Q064 "Even if parents' demands are unreasonable, children still should" +
   " do what they ask?"
   Q065 'When hiring someone, even if a stranger is more qualified, the' +
   ' opportunity should still be given to relatives and friend'
   Q066 'When one has a conflict with a neighbor, the best way to deal' +
   ' with it is to accommodate the other person?'
   Q067 'Wealth and poverty, success and failure are all determined by' +
   ' fate?'
   Q068 'A person should not insist on his own opinion if his co-workers' +
   ' disagree with him?'
   Q069 'For the sake of the family, the individual should put his' +
   ' personal interests second?'
   Q070 'A man will lose face if he works under a female supervisor?'
   Q071 'If there is a quarrel, we should ask an elder to resolve the' +
   ' dispute?'
   Q072 'When a mother-in-law and a daughter-in-law come into conflict,' +
   ' even if the mother-in-law is in the wrong, the husband sh'
   Q073 'Contacted any government official to express your opinions?'
   Q074 'Contacted officials to express your opinions at higher level?'
   Q075 'contacted elected legislative representatives at any level?'
   Q076 'Contacted political parties or other political organizations?'
   Q077 'Contacted non-government/civil society organizations?'
   Q078 'Contacted media to comment on something?'
   Q079 'Demonstrated, striken, or sat-in for something?'
   Q080 'Contacted other people?'
   Q081 'Did you do this alone or with others?_contacted government' +
   ' official'
   Q082 'Did you do this alone or with others?_contacted officials at' +
   ' higher level'
   Q083 'Did you do this alone or with others?_contacted elected' +
   ' legislative representatives at any level'
   Q084 'Did you do this alone or with others?_contacted political parties' +
   ' or other political organizations'
   Q085 'Did you do this alone or with others?_contacted no' +
   'n-government/civil society organizaions'
   Q086 'Did you do this alone or with others?_contacted media'
   Q087 'Did you do this alone or with others?_demonstration, strike,' +
   ' sit-in'
   Q088 'Did you do this alone or with others?_contacted other people'
   Q089 'Gift or dinner_contacted government'
   Q090 'Gift or dinner_contacted officials at highter level'
   Q091 'Gift or dinner_contacted elected legislative representatives'
   Q092 'Gift or dinner_contacted political parties or other political' +
   ' organizations'
   Q093 'Gift or dinner_contacted non-goverment/civil society' +
   ' organizations'
   Q094 'Gift or dinner_contacted media'
   Q095 'Gift or dinner_demonstration, strike, sit-in'
   Q096 'Gift or dinner_contacted other people'
   Q097_A 'what does democracy mean?(The first answer)'
   Q097_B 'what does democracy mean?(The second answer)'
   Q097_C 'what does democracy mean?(The third answer)'
   Q097_1 'what does democracy mean?(The first answer)'
   Q097_2 'what does democracy mean?(The second answer)'
   Q097_3 'what does democracy mean?(The third answer)'
   Q098 'Satisfaction with the way democracy works in our country?'
   Q099 'Where would you place our country during the Suchinda era?'
   Q100 'Where would you place our country under the present government?'
   Q101 'To what extent would you want our country to be democratic now?'
   Q102 'Where do you expect our country to be in five years?'
   Q103 'Do you think democracy is suitable for our country?'
   Q104 'How satisfied or dissatisfied are you with the Thaskin' +
   ' government?'
   Q105 'Everyone is free to say what they think- is better than before?'
   Q106 'Everyone is treated equally by the government- is better than' +
   ' before?'
   Q107 'People like me can have an influence on government- is better' +
   ' than before?'
   Q108 'Corruption in politics and government is under control- is better' +
   ' than before?'
   Q109 'The gap between the rich and the poor have narrowed- is better' +
   ' than before?'
   Q110 'Preventing crime and maintaining order- is better than before?'
   Q111 'Economic development- is better than before?'
   Q112 'Judges and courts are free from political interference- is better' +
   ' than before?'
   Q113 'You can join any organization you like- is better than before?'
   Q114 'How widespread corruption in your local/municipal government?'
   Q115 'How widespread corruption in the national government?'
   Q116 'Have you or anyone you know personally witnessed an act of' +
   ' corruption or bribe-taking by a politician or government offi'
   Q116E 'anyone you know personally witnessed '
   Q116A 'anyone you know personally witnessed an act of corruption?'
   Q116B 'Personal witness (2,3,4)'
   Q117 'Which comes closest to your own opinion?'
   Q118 'Which comes closer to your own view?'
   Q119 'choose between democracy and economic development?'
   Q120 'Which comes closer to your own view?'
   Q121 'We should get rid of parliament and elections and have a strong' +
   ' leader decide things'
   Q122 'No opposition party should be allowed to compete for power'
   Q123 'The military should come in to govern the country'
   Q124 'We should get rid of parliament and elections and have the' +
   ' experts decide everything'
   Q125 'It is ok for the government to disregard the law in order to deal' +
   ' with the situation, when the country is facing a diffi'
   Q126 'I have the ability to participate in politics'
   Q127 "Politics and government seems so complicated that a person like" +
   " me can't really understand what is going on"
   Q128 'The nation is run by a powerful few and ordinary citizens cannot' +
   ' do much about it'
   Q129 "People like me don't have any influence over what the government" +
   " does"
   Q130 'Our form of government is still the best for us'
   Q131 'You can generally trust the people who run our government to do' +
   ' what is right'
   Q132 'People with little or no education should have as much say in' +
   ' politics as highly-educated people'
   Q132A 'Uneducated people should have little say in government'
   Q133 'Government leaders are like the head of a family; we should all' +
   ' follow their decisions'
   Q134 'The government should decide whether certain ideas should be' +
   ' allowed to be discussed in society'
   Q135 'Harmony of the community will be disrupted if people organize' +
   ' lots of groups'
   Q136 'When judges decide important cases, they should accept the view' +
   ' of the executive branch'
   Q137 'If the government is constantly checked by the legislature, it' +
   ' cannot possibly accomplish great things'
   Q138 'If we have political leaders who are morally upright, we can let' +
   ' them decide everything'
   Q139 'If people have too many different ways of thinking, society will' +
   ' be chaotic'
   Q140 'The government should maintain ownership of major state-owned' +
   ' enterprises'
   Q141 'The national government should have more authority over local' +
   ' decisions than it does now'
   Q142 'Our country should defend our way of life instead of becoming' +
   ' more and more like other countries'
   Q143 'For the sake of the national community/society, the individual' +
   ' should be prepared to sacrifice his personal interest'
   Q144 'The state is like a big machine and the individual is but a small' +
   ' cog, with no independent status'
   Q145 'The most important thing for a political leader is to accomplish' +
   ' his goals even if he has to ignore the established proc'
   Q146 'If a political leader really believes in his position, he should' +
   ' refuse to compromise regardless of how many people disa'
   Q147 'A political leader should tolerate the views of those who' +
   ' challenge his political ideals'
   Q148 'As long as a political leader enjoys majority support, he should' +
   ' implement his own agenda and disregard the view of the '
   IR001 "Interviewer's ID"
   IR002 'First questionnaire?'
   IR002A 'Gender'
   IR002B 'Age (interviewer)'
   IR002C 'Language of the home?'
   IR003 'Others present?'
   IR003A 'Others present: who are they?'
   IR004 'Has the respondent ever refused to be interviewed during the' +
   ' whole process?'
   IR005 'Has the respondent ever felt impatient during the interview?'
   IR006 'How cooperative was the respondent during the interview?'
   IR007_1 'date of interview: month'
   IR007_2 'date of interview: day'
   IR007_3 'date of interview: year'
   IR008 'Language in which interview was conducted'
   IR009 'Was the interview conducted with the assisance of an interpreter'
   IR010A "What is the condition of the road leading to interview's" +
   " residence"
   IR010B "How do rate the sanitary condition in the public area in the" +
   " interviewee's nearby neighborhood"
   IR010C "Tell us whetherthe interviewee's residence has public water" +
   " supply"
   IR010D "Tell us whetherthe interviewee's residence has electricity"
   IR010E "Walking distance between the nearest public transportation stop" +
   " and the respondent's house"
   TH001 'Actual age(se03_1)'
   TH002 'number of household (including servants)se08c'
   TH003 'Local MP(q18_1)'
   TH004 'The Constitution Court(q18_2)'
   TH005 'The Corruption Commission(q18_3)'
   TH006 'Did you vote in the Senate election(q27_1)'
   TH007 'We should not tolerate political views that are fundamentary' +
   ' different from those of the majority(72_1).'
   TH008 'Free speech is just not worth it if  it means that we have to put' +
   ' up with the danger to society of(72_2)'
   TH009 'Positions dependent on friends or relatives in government(115_1)'
   TH010 'Politicians give money or gifts to people during an' +
   ' election(115_2)'
   TH011 'Gave donation to government official during celebration(115_3)'
   TH012 '"Tipped" government official for assistance(115_4)'
   TH013 'Some corruption in government is necessary to get things' +
   ' done(115_5)'
   W_TH 'weight' .

VALUE LABELS
 COUNTRY
     8 'Thailand' /
 CHNO
     1 'Lumpoon'
     2 'Chiangrai'
     3 'Chiangmai'
     4 'Nan'
     5 'Kampangpetch'
     6 'Tak'
     7 'Payao'
     8 'Pichit'
     9 'Pitsanulok'
     10 'petchaboon'
     11 'Sakolnakorn'
     12 'Nongkai'
     13 'Udornthani'
     14 'Karasin'
     15 'Khonkan'
     16 'Nakornpanom'
     17 'Mookdahan'
     18 'Roy-ed'
     19 'Srisaket'
     20 'Surin'
     21 'Ubonratchathani'
     22 'Chaiyapoom'
     23 'Nakornratchasrima'
     24 'Burirum'
     25 'Suratthani'
     26 'Nakornsrithammaratch'
     27 'pattanee'
     28 'Yala'
     29 'Songkla'
     30 'Trang'
     31 'Phuket'
     32 'Samudprakarn'
     33 'Chachaengsao'
     34 'Cholburi'
     35 'Bangkok'
     36 'Samudsakorn'
     37 'Singburi'
     38 'Supanburi'
     39 'Nakornsawan'
     40 'Nontaburi'
     41 'Patumthani'
     42 'Ratchaburi'
     43 'Lopburi' /
 AMPER
     1 'Lee' /
 REGION
     1 'Bangkok'
     2 'Central'
     3 'North'
     4 'Northeast'
     5 'South' /
 LEVEL1
     1 'nakorn'
     2 'meung'
     3 'tambol'
     99 'No Answer' /
 LEVEL3
     1 'urban'
     2 'rural' /
 LEVEL2_1
     1 'rural'
     2 'non-Bkk suburb'
     3 'provincial capital'
     4 'Bkk suburb'
     5 'Bkk downtown' /
 LEVEL2_2
     1 'rural'
     2 'non-Bkk suburb'
     3 'provincial capital'
     4 'Bkk suburb'
     5 'Bkk downtown' /
 LEVEL2_3
     1 'rural'
     2 'non-Bkk suburb'
     3 'provincial capital'
     4 'Bkk suburb'
     5 'Bkk downtown' /
 LEVEL3_1
     1 'urban'
     2 'rural' /
 LEVEL3_2
     1 'urban'
     2 'rural' /
 YRSURVEY
     2002 '2002' /
 SE002
     1 'male'
     2 'female'
     99 'No answer' /
 SE003
     1 '18-19'
     2 '20-24'
     3 '25-29'
     4 '30-34'
     5 '35-39'
     6 '40-44'
     7 '45-49'
     8 '50-54'
     9 '55-59'
     10 '60-70'
     11 '71-75'
     12 '76 & over'
     99 'No Answer' /
 SE003A
     18 '18'
     19 '19'
     20 '20'
     21 '21'
     22 '22'
     23 '23'
     24 '24'
     25 '25'
     26 '26'
     27 '27'
     28 '28'
     29 '29'
     30 '30'
     31 '31'
     32 '32'
     33 '33'
     34 '34'
     35 '35'
     36 '36'
     37 '37'
     38 '38'
     39 '39'
     40 '40'
     41 '41'
     42 '42'
     43 '43'
     44 '44'
     45 '45'
     46 '46'
     47 '47'
     48 '48'
     49 '49'
     50 '50'
     51 '51'
     52 '52'
     53 '53'
     54 '54'
     55 '55'
     56 '56'
     57 '57'
     58 '58'
     59 '59'
     60 '60'
     61 '61'
     62 '62'
     63 '63'
     64 '64'
     65 '65'
     66 '66'
     67 '67'
     68 '68'
     69 '69'
     70 '70'
     71 '71'
     72 '72'
     73 '73'
     74 '74'
     75 '75'
     76 '76'
     77 '77'
     78 '78'
     79 '79'
     80 '80'
     81 '81'
     82 '82'
     83 '83'
     84 '84'
     85 '85'
     86 '86'
     87 '87'
     88 '88'
     89 '89'
     90 '90'
     999 'No Answer' /
 SE004
     1 'married'
     2 'living-in as married'
     3 'widowed'
     4 'married but separate'
     5 'divorced'
     6 'single'
     99 'No Answer' /
 SE004A
     1 'Yes'
     2 'No'
     99 'No Answer' /
 SE005
     1 'no formal education'
     2 'incomplete primary'
     3 'complete primary'
     4 'complete technical school'
     5 'complete technical school at high level'
     6 'incomplete secondary high school'
     7 'complete high school'
     8 'university/college-level with diploma'
     9 'university/college degree'
     10 'post graduate degree'
     99 'No Answer' /
 SE005A
     1 '1 year'
     2 '2 years'
     3 '3 years'
     4 '4 years'
     5 '5 years'
     6 '6 years'
     7 '7 years'
     7.5 '7.5 years'
     8 '8 years'
     9 '9 years'
     10 '10 years'
     11 '11 years'
     12 '12 years'
     13 '13 years'
     14 '14 years'
     15 '15 years'
     16 '16 years'
     17 '17 years'
     18 '18 years'
     19 '19 years'
     20 '20 years'
     21 '21 years'
     22 '22 years'
     23 '23 years'
     24 '24 years'
     25 '25 years'
     99 'Np Answer' /
 SE005B
     1 'illiterate'
     2 'primary education'
     3 'secondary education'
     4 'tertitary education'
     98 "Don't Know"
     99 'No Answer' /
 SE006
     1 'Shinto'
     2 'Daoism'
     3 'Other Folk Religio'
     4 'Born again'
     5 'Buddhism'
     6 'Hinduism'
     7 'Islam'
     8 'Roman Catholics'
     9 'Protestantism'
     10 'Others'
     11 'None'
     97 'Not applicable'
     99 'No Answer' /
 SE006A
     0 'none'
     10 'Roman Catholic'
     20 'Protestant'
     30 'Jews'
     40 'Islam'
     50 'Hindu'
     60 'Buddhist'
     70 'other' /
 SE007
     1 'several time a day'
     2 'once a day'
     3 'several time a week'
     4 'once a week'
     5 'once a month'
     6 'only on special religious days'
     7 'once a year'
     8 'less often'
     9 'practically never'
     99 'No Answer' /
 SE008A
     0 'none'
     1 '1 people'
     2 '2 people'
     3 '3 people'
     4 '4 people'
     5 '5 people'
     6 '6 people'
     7 '7 people'
     8 '8 people'
     9 '9 people'
     10 '10 people'
     11 '11 people'
     12 '12 people'
     13 '13 people'
     14 '14 people'
     17 '17 people'
     18 '18 people'
     20 '20 people' /
 SE008B
     1 'one generation'
     2 'two generation'
     3 'three generation'
     4 'more than three generation'
     99 'No Answer' /
 SE009
     1 '0-1,000 baht'
     2 '1,001-5,000 baht'
     3 '5,001-10,000 baht'
     4 '10,001-20,000 baht'
     5 'mre than 20,000 baht'
     99 'No Answer' /
 SE009A
     1 'wages and salaries'
     2 'rental of property'
     3 'business income'
     4 'gift/help from relative'
     5 'pension and retirement benefit'
     6 'other, please specify'
     99 'No Answer' /
 SE012A
     1 'Admin/Manager'
     2 'Professional'
     3 'Clerical'
     4 'Sale'
     5 'Service'
     6 'Farmer'
     7 'Manual worker'
     8 'Not working'
     9 'Other'
     97 'Not Applicable'
     98 "Don't know"
     99 'No answer' /
 SE012BTH
     10 'hired workers'
     11 'professional'
     12 'manager'
     13 'clerical'
     14 'skilled'
     15 'unskilled labours'
     16 'agriculture'
     17 'employers'
     18 'agricultural operators'
     19 'non-agricultural entrepreneurs'
     20 'with 10 or more employees'
     21 'with less than 10 employees'
     22 'no employees'
     30 'purely property owners'
     31 'rental from agriculture'
     32 'retal from non-agriculture'
     33 'other'
     60 'presently unemployed and not looking for'
     61 'homecare'
     62 'student'
     63 'retired'
     64 'disabled'
     65 'other (not in labor force)'
     70 'never work before'
     71 'homecare2'
     72 'student2'
     73 'retired2'
     74 'disabled2'
     75 'other (never work)'
     80 'respondent is also the chief wage earner'
     99 'No Answer' /
 SE012C
     10 'hired workers'
     11 'professional'
     12 'manager'
     13 'clerical'
     14 'skilled'
     15 'unskilled labours'
     16 'agriculture'
     17 'employers'
     18 'agricultural operators'
     19 'non-agricultural entrepreneurs'
     20 'with 10 or more employees'
     21 'with less than 10 employees'
     22 'no employees'
     30 'purely property owners'
     31 'rental from agriculture'
     32 'retal from non-agriculture'
     33 'other'
     60 'presently unemployed and not looking for'
     61 'homecare'
     62 'student'
     63 'retired'
     64 'disabled'
     65 'other (not in labor force)'
     70 'never work before'
     71 'homecare2'
     72 'student2'
     73 'retired2'
     74 'disabled2'
     75 'other (never work)'
     80 'respondent is also the chief wage earner'
     99 'No Answer' /
 SE014
     1 'central thai'
     2 'north thai'
     3 'northeast thai'
     4 'south thai'
     5 'malay'
     6 'chinese'
     7 'mountant thai'
     8 'other'
     99 'No Answer' /
 SE017
     1 'upper class'
     2 'upper middle class'
     3 'middle class'
     4 'lower middle class'
     5 'lower class'
     97 "don't know"
     98 'none of these'
     99 'no answer' /
 RELIG1
     5 'Buddhism'
     6 'Hinduism'
     7 'Islam'
     8 'Roman Catholics'
     9 'Protestantism'
     11 'None' /
 FGNUM
     0 'None'
     1 'One'
     2 'Two'
     3 'Three' /
 PGNUM
     0 'None'
     1 'One'
     2 'Two'
     3 'Three' /
 Q001
     1 'very good'
     2 'good'
     3 'so so'
     4 'bad'
     5 'very bad'
     99 'No Answer' /
 Q002
     1 'much better'
     2 'a little better'
     3 'about the same'
     4 'a little worse'
     5 'much worse'
     99 'No Answer' /
 Q003
     1 'much better'
     2 'a little better'
     3 'about the same'
     4 'a little worse'
     5 'much worse'
     99 'No Answer' /
 Q004
     1 'very good'
     2 'good'
     3 'so so'
     4 'bad'
     5 'very bad'
     99 'No Answer' /
 Q005
     1 'much better'
     2 'a little better'
     3 'about the same'
     4 'a little worse'
     5 'much worse'
     99 'No Answer' /
 Q006
     1 'much better'
     2 'a little better'
     3 'about the same'
     4 'a little worse'
     5 'much worse'
     99 'No Answer' /
 Q007
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q008
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q009
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q010
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q011
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q012
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q013
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q014
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q015
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q016
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q017
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q018
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q018_7
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q018_8
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q018_9
     1 'none at all'
     2 'not very much trust'
     3 'quite a lot of trust'
     4 'a great deal of trust'
     99 'No Answer' /
 Q019
     1 'Member of organization or group'
     99 'Not a member of organization or group' /
 Q019_2
     0 'no'
     1 'yes' /
 Q019_3
     0 'no'
     1 'yes' /
 Q019_4
     0 'no'
     1 'yes' /
 Q019_5
     0 'no'
     1 'yes' /
 Q019_6
     0 'no'
     1 'yes' /
 Q019_7
     0 'no'
     1 'yes' /
 Q019_8
     0 'no'
     1 'yes' /
 Q019_9
     0 'no'
     1 'yes' /
 Q019_10
     0 'no'
     1 'yes' /
 Q019_11
     0 'no'
     1 'yes' /
 Q019_12
     0 'no'
     1 'yes' /
 Q019_13
     0 'no'
     1 'yes' /
 Q019_14
     0 'no'
     1 'yes' /
 Q019_15
     0 'no'
     1 'yes' /
 Q019_16
     0 'no'
     1 'yes' /
 Q020
     1 'Member of organization or group'
     99 'Not a member of organization or group' /
 Q020_2
     0 'no'
     1 'yes' /
 Q020_3
     0 'no'
     1 'yes' /
 Q020_4
     0 'no'
     1 'yes' /
 Q020_5
     0 'no'
     1 'yes' /
 Q020_6
     0 'no'
     1 'yes' /
 Q020_7
     0 'no'
     1 'yes' /
 Q020_8
     0 'no'
     1 'yes' /
 Q021
     19.1 'Citizen movement organization'
     19.11 'Religious group'
     19.12 'Alumni association'
     19.13 'Candidate support organization'
     19.14 'Political party'
     19.15 'Sport or Leisure club'
     19.16 'other association'
     19.2 'residential association'
     19.3 'PTA'
     19.4 'Trade association'
     19.5 'Agriculture association'
     19.6 'labor union'
     19.7 'Producer cooperative'
     19.8 'Consumer cooperative'
     19.9 'volunteer group'
     20.2 'Colleagues who interact outside work'
     20.3 'group at school'
     20.4 'circle of friends who share interest'
     20.5 'circle of friends who do business'
     20.6 'circle of friends who exchange information'
     20.7 'informal credit association'
     20.8 'other group'
     97 'Not Applicable' /
 Q022
     1 'never'
     2 'rarely'
     3 'sometimes'
     4 'often '
     5 'very often'
     99 'No Answer' /
 Q023
     1 'never'
     2 'rarely'
     3 'sometimes'
     4 'often '
     5 'very often'
     99 'No Answer' /
 Q024
     1 'most people can be trust'
     2 "one can't be too careful in dealing with them"
     99 'No Answer' /
 Q025
     1 'applies very well'
     2 'applies pretty well'
     3 "doesn't apply much"
     4 "doesn't apply at all"
     99 'No Answer' /
 Q026
     1 'applies very well'
     2 'applies pretty well'
     3 "doesn't apply much"
     4 "doesn't apply at all"
     99 'No Answer' /
 Q027
     1 'no'
     2 'yes'
     97 'not applicable'
     98 "don't remember"
     99 'No Answer' /
 Q028
     99 'No Answer'
     801 'Democrat'
     805 'New Aspiration'
     807 'Thai Rak Thai'
     809 'Chat Thai'
     811 'Thai Motherland'
     813 'Rassadorn'
     815 'Seritham'
     818 'Prachakorn Thai'
     821 'Chat Pattana' /
 Q029
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'No Answer' /
 Q030
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'No Answer' /
 Q031
     1 'no'
     2 'yes'
     97 'not applicable'
     99 'No Answer' /
 Q032
     1 'no'
     2 'yes' /
 Q033
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q034
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q035
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q036
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q037
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q038
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q039
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q040
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q041
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q042
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q043
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q044
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q045
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q046
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q047
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q048
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q049
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q050
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q051
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q052
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q053
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q054
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q055
     1 'no'
     2 'yes'
     99 'No Answer' /
 Q056
     1 'not at all  interested'
     2 'not very interested'
     3 ' somewhat interested'
     4 'very interested'
     98 "don't know"
     99 'No Answer' /
 Q057
     2 'practically never'
     3 'not even once a week'
     4 'once or twice a week'
     5 'several times a week'
     6 'everyday'
     99 'No Answer' /
 Q058
     2 'practically never'
     3 'not even once a week'
     4 'once or twice a week'
     5 'several times a week'
     6 'everyday'
     99 'No Answer' /
 Q059
     2 'practically never'
     3 'not even once a week'
     4 'once or twice a week'
     5 'several times a week'
     6 'everyday'
     99 'No Answer' /
 Q060
     2 'practically never'
     3 'not even once a week'
     4 'once or twice a week'
     5 'several times a week'
     6 'everyday'
     99 'No Answer' /
 Q061
     1 'no impact at all'
     2 'a little impact'
     3 'quite some impact'
     4 'a great deal of impact'
     99 'No Answer' /
 Q062
     99 'not feel close to any'
     801 'Democrat'
     802 'Thai rak Thai'
     803 'Chat thai'
     804 'Chat Pattana'
     805 'Rassadorn'
     806 'Kuamwangmai'
     807 'Thai Motherland'
     808 'Seritham'
     809 'other' /
 Q063
     1 'just a little close'
     2 'somewhat close'
     3 'very close'
     99 'No answer' /
 Q064
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q065
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q066
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q067
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q068
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q069
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q070
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q071
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q072
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q073
     1 'once'
     2 'more than once'
     9 'never' /
 Q074
     1 'once'
     2 'more than once'
     9 'never' /
 Q075
     1 'once'
     2 'more than once'
     9 'never' /
 Q076
     1 'once'
     2 'more than once'
     9 'never' /
 Q077
     1 'once'
     2 'more than once'
     9 'never' /
 Q078
     1 'once'
     2 'more than once'
     9 'never' /
 Q079
     1 'once'
     2 'more than once'
     9 'never' /
 Q080
     1 'once'
     2 'more than once'
     9 'never' /
 Q097_A
     1 'right and freedom'
     2 'equality'
     3 'majority'
     4 'participation'
     99 'No Answer' /
 Q097_B
     1 'right and freedom'
     2 'equality'
     3 'majority'
     4 'participation'
     99 'No Answer' /
 Q097_C
     1 'right and freedom'
     2 'equality'
     3 'majority'
     4 'participation'
     99 'No Answer' /
 Q097_1
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_2
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_3
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q098
     1 'not at all satisfied'
     2 'not very satisfied'
     3 'fairly satisfied'
     4 'very satisfied'
     99 'No Answer' /
 Q099
     1 'complete dictatorship'
     10 'complete democracy'
     99 'No Answer' /
 Q100
     1 'complete dictatorship'
     10 'complete democracy'
     99 'No Answer' /
 Q101
     1 'complete dictatorship'
     10 'complete democracy'
     99 'No Answer' /
 Q102
     1 'complete dictatorship'
     10 'complete democracy'
     99 'No Answer' /
 Q103
     1 'democracy is completely unsuitable'
     10 'democracy is perfectly suitable'
     99 'No Answer' /
 Q104
     1 'very dissatisfied'
     2 'somewhat dissatisfied'
     3 'somewhat satisfied'
     4 'very satisfied'
     99 'No Answer' /
 Q105
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q106
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q107
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q108
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q109
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q110
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q111
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q112
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q113
     1 'very worse'
     2 'somewhat worse'
     3 'much the same'
     4 'somewhat better'
     5 'much better than before'
     99 'No Answer' /
 Q114
     1 'almost everyone is corrupt'
     2 'most officials are corrupt'
     3 'not a lot of officials are corrupt'
     4 'hardly anyone is involve'
     99 'No answer' /
 Q115
     1 'almost everyone is corrupt'
     2 'most officials are corrupt'
     3 'not a lot of officials are corrupt'
     4 'hardly anyone is involve'
     99 'No answer' /
 Q116
     1 'Yes'
     2 'No'
     98 "Don't know"
     99 'No answer' /
 Q116E
     1 'Personally'
     2 'Family member'
     3 'Friend'
     4 'None'
     99 'No Answer' /
 Q116A
     1 'witnessed'
     5 'personally never witnessed'
     6 'no one I know has personally witnessed'
     99 'No Answer' /
 Q116B
     2 'personally witnessed'
     3 'told about it by a family member'
     4 'told about it by a friend'
     5 'MYSELF AND FAMILY/MYSELF AND FRIENDS'
     6 ' FAMILY AND FRIENDS'
     7 'MYSELF AND FAMILY AND FRIENDS'
     8 'personally witnessed and told by friend'
     9 'personally witnessed and told by family'
     10 'told about it by a family member and friend'
     13 'personally witnessed and told by a family member and friend'
     99 'No Answer' /
 Q117
     1 'under some circumstance authoritarian can be preferable'
     2 "for people like me it doesn't not matter"
     3 'democracy is always preferable'
     99 'No Answer' /
 Q118
     1 'democracy can not solve'
     2 'democracy is capable'
     99 'No Answer' /
 Q119
     1 'economic development is definitely more important'
     2 'economic development is somewhat more important'
     3 'democracy is somewhat more important'
     4 'democracy is definitely more important'
     5 'they are both equally important'
     99 'No Answer' /
 Q120
     1 'remain one nation'
     2 'should be allowed to become fully separate'
     3 'can not choose'
     99 'No Answer' /
 Q121
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q122
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q123
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q124
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q125
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q126
     1 'strongly dsiagree'
     2 'somewhat disagree'
     3 'somewhat agree'
     4 'strongly agree'
     99 'No Answer' /
 Q127
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q128
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q129
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q130
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q131
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q132
     1 'strongly dsiagree'
     2 'somewhat disagree'
     3 'somewhat agree'
     4 'strongly agree'
     99 'No Answer' /
 Q132A
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q133
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q134
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q135
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q136
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q137
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q138
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q139
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q140
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q141
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q142
     1 'strongly dsiagree'
     2 'somewhat disagree'
     3 'somewhat agree'
     4 'strongly agree'
     99 'No Answer' /
 Q143
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q144
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q145
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q146
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 Q147
     1 'strongly dsiagree'
     2 'somewhat disagree'
     3 'somewhat agree'
     4 'strongly agree'
     99 'No Answer' /
 Q148
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'No Answer' /
 IR001
     0 '0'
     1 '1'
     2 '2'
     3 '3'
     4 '4'
     5 '5'
     6 '6'
     7 '7'
     8 '8'
     9 '9'
     10 '10'
     203 '203'
     301 '301'
     302 '302'
     303 '303'
     304 '304'
     305 '305'
     306 '306'
     9999 'No Answer' /
 IR002
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR002A
     1 'male'
     2 'female'
     99 'No Answer' /
 IR002B
     18 '18'
     19 '19'
     20 '20'
     21 '21'
     22 '22'
     23 '23'
     24 '24'
     25 '25'
     26 '26'
     27 '27'
     28 '28'
     29 '29'
     30 '30'
     31 '31'
     32 '32'
     33 '33'
     34 '34'
     35 '35'
     36 '36'
     37 '37'
     38 '38'
     39 '39'
     40 '40'
     41 '41'
     42 '42'
     43 '43'
     44 '44'
     45 '45'
     46 '46'
     47 '47'
     48 '48'
     49 '49'
     50 '50'
     51 '51'
     52 '52'
     53 '53'
     54 '54'
     55 '55'
     56 '56'
     57 '57'
     58 '58'
     59 '59'
     60 '60'
     61 '61'
     62 '62'
     63 '63'
     64 '64'
     65 '65'
     66 '66'
     67 '67'
     68 '68'
     69 '69'
     70 '70'
     71 '71'
     72 '72'
     73 '73'
     74 '74'
     75 '75'
     76 '76'
     77 '77'
     78 '78'
     79 '79'
     80 '80'
     81 '81'
     82 '82'
     83 '83'
     84 '84'
     85 '85'
     86 '86'
     87 '87'
     88 '88'
     89 '89'
     90 '90'
     99 'No Answer' /
 IR002C
     1 'central thai'
     2 'north thai'
     3 'northeast thai'
     4 'south thai'
     5 'malay'
     6 'chinese'
     7 'mountant thai'
     8 'other'
     99 'No Answer' /
 IR003
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR003A
     1 'spouse'
     2 'children'
     3 'parent or parent-in-law'
     4 'spouse and children'
     5 'spouse and parents'
     6 'spouse and other'
     7 'children and parents'
     8 'children and other'
     9 'parent and other'
     10 'spouse children and parents'
     11 'spouse children and other'
     12 'spouse parents and other'
     13 'children parents and other'
     14 'spouse children parents and other'
     99 'No Answer' /
 IR004
     1 'yes, right at beginning'
     2 'yes, in the middle'
     3 'yes, toward the end'
     4 'never'
     99 'No Answer' /
 IR005
     1 'never'
     2 'occasionally'
     3 'sometimes'
     4 'always'
     99 'No Answer' /
 IR006
     1 'highly cooperative'
     2 'fairly cooperative'
     3 'not very cooperative'
     99 'No Answer' /
 IR007_1
     1 '1'
     10 '10'
     11 '11'
     12 '12'
     99 'No Answer' /
 IR007_2
     1 '1'
     2 '2'
     3 '3'
     4 '4'
     5 '5'
     6 '6'
     7 '7'
     8 '8'
     9 '9'
     10 '10'
     11 '11'
     12 '12'
     13 '13'
     14 '14'
     15 '15'
     16 '16'
     17 '17'
     18 '18'
     19 '19'
     20 '20'
     21 '21'
     22 '22'
     23 '23'
     24 '24'
     25 '25'
     26 '26'
     27 '27'
     28 '28'
     29 '29'
     30 '30'
     31 '31'
     99 'No Answer' /
 IR007_3
     2001 '2001'
     2002 '2002'
     9999 'No Answer' /
 IR008
     1 'central thai'
     2 'north thai'
     3 'northeast thai'
     4 'south thai'
     5 'malay'
     6 'chinese'
     7 'mountant thai'
     8 'other'
     99 'No Answer' /
 IR009
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR010A
     1 ' WIDE ENOUGH FOR CAR AND PAVED WITH ASPHALT,CEMENT OR MAN-MA'
     2 ' NOT WIDE ENOUGH FOR CAR BUT PAVED WITH ASPHALT,CEMENT OR MA'
     3 'Paved with stone'
     4 ' WIDE ENOUGH FOR CAR AND PAVED WITH STONE'
     5 ' NOT WIDE ENOUGH FOR CAR,BUT PAVED WITH STONE'
     6 'Unpaved/dirt road'
     7 ' WIDE ENOUGH FOR CAR AND UNPAVED/DIRT ROAD'
     8 ' NOT WIDE ENOUGHT FOR CAR BUT UNPAVED/DIRT ROAD'
     9 '.Muddy'
     10 ' WIDE ENOUGH FOR CAR AND MUDDY'
     11 ' NOT WIDE ENOUGH FOR CAR,BUT MUDDY'
     99 'No Answer' /
 IR010B
     1 'very bad'
     2 'somewhat bad'
     3 'So so'
     4 'fairly good'
     5 'very good'
     99 'No Answer' /
 IR010C
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR010D
     1 'yes'
     2 'no'
     99 'No Answer' /
 IR010E
     1 'less than 10 min. by walking'
     2 'less than 20 min. by walking'
     3 'less than 40 min. by walking'
     4 'less than an hour by walking'
     5 'less than two hours by walking'
     6 'less than three hours'
     7 'less than four hours by walking'
     8 'more than fours hours'
     99 'No Answer' /
 TH002
     0 'No Response' /
 TH003
     0 'No Response'
     1 'a great deal of trust'
     2 'quite a lot of trust'
     3 'not very much trust'
     4 'none at all' /
 TH004
     0 'No Response'
     1 'a great deal of trust'
     2 'quite a lot of trust'
     3 'not very much trust'
     4 'none at all' /
 TH005
     0 'No Response'
     1 'a great deal of trust'
     2 'quite a lot of trust'
     3 'not very much trust'
     4 'none at all' /
 TH006
     1 'yes'
     2 'no'
     97 'not applicable'
     99 'No Answer' /
 TH007
     0 'No Response'
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree' /
 TH008
     0 'No Response'
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree' /
 TH009
     0 'No Response'
     1 'not bad'
     2 'bribery'
     3 'corruption'
     99 'no answer' /
 TH010
     0 'No Response'
     1 'gift'
     2 'bribery'
     3 'corruption'
     99 'no answer' /
 TH011
     0 'No Response'
     1 'gift'
     2 'bribery'
     3 'corruption'
     99 'no answer' /
 TH012
     0 'No Response'
     1 'gift'
     2 'bribery'
     3 'corruption'
     99 'no answer' /
 TH013
     1 'strongly agree'
     2 'somewhat agree'
     3 'somewhat disagree'
     4 'strongly disagree'
     99 'no answer' / .

/* User Missing Value Specifications */
MISSING VALUES
  LEVEL1 (99)              SE002 (99)               SE003 (99)             
  SE003A (999)             SE004 (99)               SE004A (99)            
  SE005 (99)               SE005A (99)              SE005B (99)            
  SE007 (99)               SE008B (99)              SE009 (99)             
  SE009A (99)              SE012A (97, 98, 99)      SE012BTH (99)          
  SE012C (99)              SE014 (99)               SE017 (97, 98, 99)     
  Q001 (0, 99)             Q002 (0, 99)             Q003 (0, 99)           
  Q004 (0, 99)             Q005 (0, 99)             Q006 (99)              
  Q007 (99)                Q008 (99)                Q009 (99)              
  Q010 (99)                Q011 (99)                Q012 (99)              
  Q013 (99)                Q014 (99)                Q015 (99)              
  Q016 (99)                Q017 (99)                Q018 (99)              
  Q018_7 (99)              Q018_8 (99)              Q018_9 (99)            
  Q021 (97)                Q022 (99)                Q023 (99)              
  Q024 (99)                Q025 (99)                Q026 (99)              
  Q027 (97, 99)            Q028 (99)                Q029 (0, 99)           
  Q030 (0, 99)             Q031 (0, 99)             Q032 (0)               
  Q033 (99)                Q034 (99)                Q035 (99)              
  Q036 (99)                Q037 (99)                Q038 (99)              
  Q039 (99)                Q040 (99)                Q041 (99)              
  Q042 (99)                Q043 (99)                Q044 (99)              
  Q045 (99)                Q046 (99)                Q047 (99)              
  Q048 (99)                Q049 (99)                Q050 (99)              
  Q051 (99)                Q052 (99)                Q053 (99)              
  Q054 (99)                Q055 (99)                Q056 (99)              
  Q057 (99)                Q058 (99)                Q059 (99)              
  Q060 (99)                Q061 (99)                Q062 (99)              
  Q063 (0, 99)             Q064 (99)                Q065 (99)              
  Q066 (99)                Q067 (99)                Q068 (99)              
  Q069 (99)                Q070 (99)                Q071 (99)              
  Q072 (99)                Q097_A (99)              Q097_B (99)            
  Q097_C (99)              Q097_1 (97, 98, 99)      Q097_2 (97, 98, 99)    
  Q097_3 (97, 98, 99)      Q098 (99)                Q099 (99)              
  Q100 (99)                Q101 (99)                Q102 (99)              
  Q103 (99)                Q104 (99)                Q105 (99)              
  Q106 (99)                Q107 (99)                Q108 (99)              
  Q109 (99)                Q110 (99)                Q111 (99)              
  Q112 (99)                Q113 (99)                Q114 (99)              
  Q115 (99)                Q116 (99)                Q116E (99)             
  Q116B (99)               Q117 (99)                Q118 (99)              
  Q119 (99)                Q120 (99)                Q121 (99)              
  Q122 (99)                Q123 (99)                Q124 (99)              
  Q125 (99)                Q126 (99)                Q127 (99)              
  Q128 (99)                Q129 (99)                Q130 (99)              
  Q131 (99)                Q132 (99)                Q132A (99)             
  Q133 (99)                Q134 (99)                Q135 (99)              
  Q136 (99)                Q137 (99)                Q138 (99)              
  Q139 (99)                Q140 (99)                Q141 (99)              
  Q142 (99)                Q143 (99)                Q144 (99)              
  Q145 (99)                Q146 (99)                Q147 (99)              
  Q148 (99)                IR001 (9999)             IR002 (99)             
  IR002A (99)              IR002B (99)              IR002C (99)            
  IR003 (99)               IR003A (99)              IR004 (99)             
  IR005 (99)               IR006 (99)               IR007_1 (99)           
  IR007_2 (99)             IR007_3 (9999)           IR008 (99)             
  IR009 (99)               IR010A (99)              IR010B (99)            
  IR010C (99)              IR010D (99)              IR010E (99)            
  TH001 (0)                TH002 (0)                TH003 (0)              
  TH004 (0)                TH005 (0)                TH006 (97, 99)         
  TH007 (0)                TH008 (0)                TH009 (99)             
  TH010 (99)               TH011 (99)               TH012 (99)             
  TH013 (99) .
         

SAVE OUTFILE='.\thailand v4.2.sav'.
