import numpy as np

w1_column_mapping = {
    "se003": "agegroup",
    "se004a": "married",
    "se005a": "educyear",
    "level3": "urban_rural",
    "se002": "gender",
    "se003a": "age",
    "se004": "maritalstatus",
    "se004a": "married",
    "se005": "education",
    "se005a": "educationyear",
    "se009": "income_quintile",
    "se006": "religion",
    "se008b": "generations",
    "se014": "language",
    "se017": "socialstatus",
    "relig1": "religion2",
    "fgnum": "num_formal_group",
}

w1_response_mapping = {
    "country": {
        1.0: "Japan",
        2.0: "Hong Kong",
        3.0: "Korea",
        4.0: "Mainland China",
        5.0: "Mongolia",
        6.0: "Philippines",
        7.0: "Taiwan",
        8.0: "Thailand",
    },
    "level3": {1.0: "urban", 2.0: "rural", 3.0: "no registration"},
    "yrsurvey": {2001.0: "2001", 2002.0: "2002", 2003.0: "2003"},
    "se002": {1.0: "male", 2.0: "female", 99.0: "No Answer"},
    "se003": {
        1.0: "18-19",
        2.0: "20-24",
        3.0: "25-29",
        4.0: "30-34",
        5.0: "35-39",
        6.0: "40-44",
        7.0: "45-49",
        8.0: "50-54",
        9.0: "55-59",
        10.0: "60-70",
        11.0: "71-75",
        12.0: "76 & over",
        99.0: "No Answer",
    },
    "se003a": {
        18.0: "18",
        19.0: "19",
        20.0: "20",
        21.0: "21",
        22.0: "22",
        23.0: "23",
        24.0: "24",
        25.0: "25",
        26.0: "26",
        27.0: "27",
        28.0: "28",
        29.0: "29",
        30.0: "30",
        31.0: "31",
        32.0: "32",
        33.0: "33",
        34.0: "34",
        35.0: "35",
        36.0: "36",
        37.0: "37",
        38.0: "38",
        39.0: "39",
        40.0: "40",
        41.0: "41",
        42.0: "42",
        43.0: "43",
        44.0: "44",
        45.0: "45",
        46.0: "46",
        47.0: "47",
        48.0: "48",
        49.0: "49",
        50.0: "50",
        51.0: "51",
        52.0: "52",
        53.0: "53",
        54.0: "54",
        55.0: "55",
        56.0: "56",
        57.0: "57",
        58.0: "58",
        59.0: "59",
        60.0: "60",
        61.0: "61",
        62.0: "62",
        63.0: "63",
        64.0: "64",
        65.0: "65",
        66.0: "66",
        67.0: "67",
        68.0: "68",
        69.0: "69",
        70.0: "70",
        71.0: "71",
        72.0: "72",
        73.0: "73",
        74.0: "74",
        75.0: "75",
        76.0: "76",
        77.0: "77",
        78.0: "78",
        79.0: "79",
        80.0: "80",
        81.0: "81",
        82.0: "82",
        83.0: "83",
        84.0: "84",
        85.0: "85",
        86.0: "86",
        87.0: "87",
        88.0: "88",
        89.0: "89",
        90.0: "90",
        93.0: "93",
        109.0: "109",
        999.0: "No Answer",
    },
    "se004": {
        1.0: "Married",
        2.0: "Living-in as married",
        3.0: "Widowed",
        4.0: "Separated",
        5.0: "Divorced",
        6.0: "Single_Never married",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "se004a": {1.0: "Yes", 2.0: "No", 98.0: "Don't Know", 99.0: "No Answer"},
    "se005": {
        1.0: "No formal education",
        2.0: "Incomplete elementary school",
        3.0: "Complete elementary school",
        4.0: "Incomplete secondary school",
        5.0: "Complete secondary school",
        6.0: "Incomplete high school",
        7.0: "Complete high school",
        8.0: "Some university_college education",
        9.0: "University_college degree",
        10.0: "Post graduate degree",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "se005a": {
        0.0: "less than 1 year",
        1.0: "1 years",
        2.0: "2 years",
        3.0: "3 years",
        4.0: "4 years",
        5.0: "5 years",
        6.0: "6 years",
        7.0: "7 years",
        8.0: "8 years",
        9.0: "9 years",
        10.0: "10 years",
        11.0: "11 years",
        12.0: "12 years",
        13.0: "13 years",
        14.0: "14 years",
        15.0: "15 years",
        16.0: "16 years",
        17.0: "17 years",
        18.0: "18 years",
        19.0: "19 years",
        20.0: "20 years",
        21.0: "21 years",
        22.0: "22 years",
        23.0: "23 years",
        24.0: "24 years",
        25.0: "25 years",
        30.0: "30 years",
        44.0: "44 years",
        97.0: "Not applicable",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "se009": {
        1.0: "lowest quintile",
        2.0: "2nd quintile",
        3.0: "3rd quintile",
        4.0: "4th quintile",
        5.0: "5th quintile",
        97.0: "Not applicable",
        98.0: "Don't Know",
        99.0: "No Answer",
    },
    "q005": {
        1.0: "Much worse now",
        2.0: "A little worse now",
        3.0: "About the same",
        4.0: "A little better now",
        5.0: "Much better now",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q006": {
        1.0: "Much Worse",
        2.0: "A little Worse",
        3.0: "About the same",
        4.0: "A little Better",
        5.0: "Much Better",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q007": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q008": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q009": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q010": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q027": {
        1.0: "No",
        2.0: "Yes",
        97.0: "Not applicable",
        98.0: "Don't remember",
        99.0: "No answer",
    },
    "q028": {
        96.0: "Forgot",
        97.0: "Not applicable",
        98.0: "Don't know",
        99.0: "No answer",
        101.0: "LDP",
        102.0: "DPJ",
        103.0: "New Komeito",
        104.0: "SDP",
        105.0: "JCP",
        106.0: "NCP",
        107.0: "LP",
        108.0: "Other parties",
        109.0: "Not affiliated",
        301.0: "Lee Hoi-chang",
        302.0: "Roh Moo-hyun",
        303.0: "Kwon Young-ghil",
        304.0: "Jang Se-Dong",
        501.0: "MAHN",
        502.0: "AN",
        503.0: "MAShSN",
        504.0: "IZ-BNN",
        505.0: "other",
        701.0: "James Chu Yu Soong",
        702.0: "Chan Lien",
        703.0: "Ao Lee",
        704.0: "Hsin-liang Hsu",
        705.0: "Shui-bian Chen",
        801.0: "Democrat",
        805.0: "New Aspiration",
        807.0: "Thai Rak Thai",
        809.0: "Chat Thai",
        811.0: "Thai Motherland",
        813.0: "Rassadorn",
        815.0: "Seritham",
        818.0: "Prachakorn Thai",
        821.0: "Chat Pattana",
    },
    "q098": {
        1.0: "Not at all satisfied",
        2.0: "Not very satisfied",
        3.0: "Fairly satisfied",
        4.0: "Very satisfied",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q105": {
        1.0: "Much worse",
        2.0: "Somewhat worse",
        3.0: "Much the same",
        4.0: "Somewhat better",
        5.0: "Much better than before",
        97.0: "Not Applicable",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q106": {
        1.0: "Much worse",
        2.0: "Somewhat worse",
        3.0: "Much the same",
        4.0: "Somewhat better",
        5.0: "Much better than before",
        97.0: "Not Applicable",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q121": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q123": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q127": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q128": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "se006": {
        1.0: "Shinto",
        2.0: "Daoism",
        3.0: "Other Folk Religio",
        4.0: "Born again",
        5.0: "Buddhism",
        6.0: "Hinduism",
        7.0: "Islam",
        8.0: "Roman Catholics",
        9.0: "Protestantism",
        10.0: "Others",
        11.0: "None",
        97.0: "Not applicable",
        99.0: "No Answer",
    },
    "se008b": {
        1.0: "1 generation",
        2.0: "2 generations",
        3.0: "3 generations",
        4.0: "more than 4 generations",
        98.0: "don't know",
        99.0: "No Answer",
    },
    "se014": {
        1.0: "ONLY LOCAL DIALECT",
        2.0: "LOCAL DIALECT MOST TIME",
        3.0: "COMBINATION",
        4.0: "PUTONGHUA MOST TIME",
        5.0: "ONLY PUTONGHUA",
        6.0: "Other",
        7.0: "Do not understand",
        8.0: "Can't choose",
        99.0: "NO ANSWER",
    },
    "se017": {
        1.0: "Upper class",
        2.0: "Upper middle class",
        3.0: "Middle class",
        4.0: "Lower-Middle class",
        5.0: "Lower class",
        97.0: "Don't know",
        98.0: "None of these",
        99.0: "No Answer",
    },
    "relig1": {
        1.0: "Shinto",
        2.0: "Daoism",
        3.0: "Other Folk Religio",
        4.0: "Born again",
        5.0: "Buddhism",
        6.0: "Hinduism",
        7.0: "Islam",
        8.0: "Roman Catholics",
        9.0: "Protestantism",
        10.0: "Others",
        11.0: "None",
        97.0: "Not applicable",
        99.0: "No Answer",
    },
    "fgnum": {0.0: "None", 1.0: "One", 2.0: "Two", 3.0: "Three", 99.0: "No Answer"},
}

w2_column_mapping = {
    "level3": "urban_rural",
    "se2": "gender",
    "se3a": "age",
    "se4": "maritalstatus",
    "se5": "education",
    "se9": "income_quintile",
    "fgnum": "num_formal_group",
    "se6": "religion",
    "se8b": "generations",
    "se11": "language",
    "se13": "socialstatus",
}

w2_response_mapping = {
    "country": {
        1.0: "Japan",
        2.0: "Hong Kong",
        3.0: "Korea",
        4.0: "Mainland China",
        5.0: "Mongolia",
        6.0: "Philippines",
        7.0: "Taiwan",
        8.0: "Thailand",
        9.0: "Indonesia",
        10.0: "Singapore",
        11.0: "Vietnam",
        12.0: "Cambodia",
        13.0: "Malaysia",
    },
    "level3": {1.0: "Urban", 2.0: "Rural", 3.0: "No registration"},
    "q1": {
        1.0: "Very bad",
        2.0: "Bad",
        3.0: "So so (not good nor bad)",
        4.0: "Good",
        5.0: "Very good",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q2": {
        1.0: "Much worse",
        2.0: "A little worse",
        3.0: "About the same",
        4.0: "A little better",
        5.0: "Much better",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q3": {
        1.0: "Much worse",
        2.0: "A little worse",
        3.0: "About the same",
        4.0: "A little better",
        5.0: "Much better",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q4": {
        1.0: "Very bad",
        2.0: "Bad",
        3.0: "So so (not good nor bad)",
        4.0: "Good",
        5.0: "Very good",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q5": {
        1.0: "Much worse now",
        2.0: "A little worse now",
        3.0: "About the same",
        4.0: "A little better now",
        5.0: "Much better now",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q6": {
        1.0: "Much worse",
        2.0: "A little worse",
        3.0: "About the same",
        4.0: "A little better",
        5.0: "Much better",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q7": {
        1.0: "None at all",
        2.0: "Not Very Much Trust",
        3.0: "Quite a Lot of Trust",
        4.0: "A Great Deal of Trust",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q8": {
        1.0: "None at all",
        2.0: "Not Very Much Trust",
        3.0: "Quite a Lot of Trust",
        4.0: "A Great Deal of Trust",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q9": {
        1.0: "None at all",
        2.0: "Not Very Much Trust",
        3.0: "Quite a Lot of Trust",
        4.0: "A Great Deal of Trust",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q12": {
        1.0: "None at all",
        2.0: "Not Very Much Trust",
        3.0: "Quite a Lot of Trust",
        4.0: "A Great Deal of Trust",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q13": {
        1.0: "None at all",
        2.0: "Not Very Much Trust",
        3.0: "Quite a Lot of Trust",
        4.0: "A Great Deal of Trust",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q32": {
        1.0: "Very safe",
        2.0: "Safe",
        3.0: "Unsafe",
        4.0: "Very unsafe",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q38": {
        0.0: "Not applicable",
        1.0: "No",
        2.0: "Yes",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q40": {
        0.0: "Not applicable",
        1.0: "No",
        2.0: "Yes",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q48": {
        1.0: "Very good",
        2.0: "Good",
        3.0: "Average",
        4.0: "Bad",
        5.0: "Very bad",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q49": {
        1.0: "Not at all interested",
        2.0: "Not very interested",
        3.0: "Somewhat interested",
        4.0: "Very interested",
        7.0: "No answer",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q93": {
        1.0: "Not at all satisfied",
        2.0: "Not very satisfied",
        3.0: "Fairly satisfied",
        4.0: "Very satisfied",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q94": {
        1.0: "A full democracy",
        2.0: "A democracy, but with minor problems",
        3.0: "A democracy, with major problems",
        4.0: "Not a democracy",
        7.0: "Don't understand question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q103": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q104": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q108": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q110": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q124": {
        1.0: "Strongly approve",
        2.0: "Approve",
        3.0: "Disapprove",
        4.0: "Strongly Disapprove",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q126": {
        1.0: "Strongly approve",
        2.0: "Approve",
        3.0: "Disapprove",
        4.0: "Strongly Disapprove",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q128": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "q130": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        7.0: "Do not understand the question",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
    "se2": {1.0: "Male", 2.0: "Female"},
    "se3a": {97.0: "NO ANSWER", 98.0: "DON'T KNOW", 99.0: "REFUSED"},
    "se4": {
        1.0: "Single/Never married",
        2.0: "Married",
        3.0: "Living-in as married",
        4.0: "Widowed",
        5.0: "Separated/Married but separated/not living with legal spouse",
        6.0: "Divorced",
        9.0: "Decline to answer",
    },
    "se5": {
        1.0: "No formal education",
        2.0: "Incomplete primary/elementary",
        3.0: "Complete primary/elementary",
        4.0: "Incomplete secondary/high school: technical/vocational type",
        5.0: "Complete secondary/high school: technical/vocational type",
        6.0: "Incomplete secondary/high school",
        7.0: "Complete secondary/high school",
        8.0: "Some university education",
        9.0: "University education completed",
        10.0: "Post-graduate degree",
        11.0: "Other",
        99.0: "Decline to answer",
    },
    "se9": {
        1.0: "lowest quintile",
        2.0: "2nd quintile",
        3.0: "3rd quintile",
        4.0: "4th quintile",
        5.0: "top quintile",
        97.0: "Not applicable",
        98.0: "Can't choose",
        99.0: "Decline to answer",
    },
    "fgnum": {
        0.0: "None",
        1.0: "One",
        2.0: "Two",
        3.0: "Three",
        98.0: "Not applicable",
    },
    "se6": {
        1.0: "Traditional folk religion (Shenism)",
        10.0: "Roman Catholic",
        20.0: "Protestant",
        21.0: "Seventh Day Adventist",
        22.0: "Baptist",
        23.0: "Pentecostal",
        24.0: "Evangelical",
        25.0: "Epescopal",
        26.0: "Methodist",
        27.0: "Grace Gospel of Church",
        30.0: "Jews",
        40.0: "Islam",
        41.0: "Shia",
        42.0: "Sunni",
        50.0: "Hindu",
        60.0: "Buddhist",
        70.0: "Other Asian religions",
        71.0: "Sikhism",
        72.0: "Iglesia Ni Cristo",
        73.0: "Aglipayan",
        74.0: "Born Again",
        75.0: "Shinto",
        76.0: "Taoism",
        77.0: "I-Kuan Tao",
        78.0: "Confucianism",
        79.0: "Tiruray",
        80.0: "Other",
        81.0: "Jehovah Witness",
        82.0: "Mormons",
        83.0: "Dating Daan",
        84.0: "Anglican",
        85.0: "Baha'i",
        86.0: "Animism",
        90.0: "None",
        98.0: "Cannot choose",
        99.0: "Decline to answer",
    },
    "se8b": {
        1.0: "One generation",
        2.0: "Two generations",
        3.0: "Three generations",
        4.0: "More than three generations",
        8.0: "Don't know",
        9.0: "Decline to answer",
    },
    "se11": {
        1.0: "Only local language",
        2.0: "Mostly local language",
        3.0: "A mixture of local and official language",
        4.0: "Mostly official language",
        5.0: "Only official language",
        6.0: "Others",
        8.0: "Can't choose",
        9.0: "Decline to answer",
    },
}

w1_newq_mapping = {
    "q001": {
        1.0: "Very Bad",
        2.0: "Bad",
        3.0: "So so",
        4.0: "Good",
        5.0: "Very Good",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q002": {
        1.0: "Much Worse",
        2.0: "A little Worse",
        3.0: "About the same",
        4.0: "A little Better",
        5.0: "Much Better",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q003": {
        1.0: "Much Worse",
        2.0: "A little Worse",
        3.0: "About the same",
        4.0: "A little Better",
        5.0: "Much Better",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q004": {
        1.0: "Very Bad",
        2.0: "Bad",
        3.0: "So so",
        4.0: "Good",
        5.0: "Very Good",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q005": {
        1.0: "Much worse now",
        2.0: "A little worse now",
        3.0: "About the same",
        4.0: "A little better now",
        5.0: "Much better now",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q006": {
        1.0: "Much Worse",
        2.0: "A little Worse",
        3.0: "About the same",
        4.0: "A little Better",
        5.0: "Much Better",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q007": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q008": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q009": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q010": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q011": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q013": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q014": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q016": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q017": {
        0.0: "Not sure",
        1.0: "None at all",
        2.0: "Not very much trust",
        3.0: "Quite a lot of trust",
        4.0: "A great deal of trust",
        98.0: "Don't know",
        99.0: "No Answer",
    },
    "q024": {
        1.0: "One can't be too careful in dealing with them",
        2.0: "Most people can be trusted",
        3.0: "Both",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q027": {
        1.0: "No",
        2.0: "Yes",
        97.0: "Not applicable",
        98.0: "Don't remember",
        99.0: "No answer",
    },
    "q029": {
        1.0: "No",
        2.0: "Yes",
        97.0: "Not applicable",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q030": {
        1.0: "No",
        2.0: "Yes",
        97.0: "Not applicable",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q031": {
        1.0: "No",
        2.0: "Yes",
        97.0: "Not applicable",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q056": {
        1.0: "Not at all interested",
        2.0: "Not very interested",
        3.0: "Somewhat interested",
        4.0: "Very interested",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q057": {
        2.0: "Practically never",
        3.0: "Not even once a week",
        4.0: "Once or twice a week",
        5.0: "Several times a week",
        6.0: "Everyday",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q061": {
        1.0: "No impact at all",
        2.0: "A little impact",
        3.0: "Quite some impact",
        4.0: "A great deal of impact",
        97.0: "Not applicable",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q062": {
        97.0: "Don't know",
        98.0: "No answer",
        99.0: "Don't feel close to any political party",
        101.0: "LDP",
        102.0: "DPJ",
        103.0: "New Komeito",
        104.0: "SDP",
        105.0: "JCP",
        106.0: "NCP",
        107.0: "LP",
        108.0: "other",
        201.0: "DEMOCRATIC PARTY",
        202.0: "LIBERAL PARTY",
        203.0: "DAB",
        204.0: "THE FRONTIER",
        205.0: "HKADPL",
        206.0: "CITIZENS PARTY",
        207.0: "HK PROGRESSIVE ALLIANCE",
        209.0: "FEDERATION OF TRADE UNIONS",
        210.0: "KUOMINTANG",
        301.0: "Democratic party",
        302.0: "Grand National party",
        303.0: "United Liberal Democrats",
        304.0: "Democratic Labor party",
        305.0: "Others",
        501.0: "MAHN",
        502.0: "AN",
        503.0: "IZ-BNN",
        504.0: "MASnSN",
        505.0: "others",
        601.0: " LABAN NG DEMOKRATIKONG PILIPINO",
        602.0: " LAKAS NG TAO-NATIONAL UNION OF CHRISTIAN DEMOCRATS-UNITED M",
        603.0: " LIBERAL PARTY",
        604.0: " NACIONALISTA PARTY",
        605.0: " NATIONALIST PEOPLES COALITION",
        606.0: " PARTIDO NG MASANG PILIPINO",
        607.0: " PHILIPPINE DEMOCRATIC PARTY-LAKAS NG BAYAN",
        608.0: " PING LACSON PARTY",
        609.0: " KBL",
        610.0: " PROMDI",
        611.0: " ESTRADA PARTY",
        612.0: " PUWERSA NG MASA",
        613.0: " GLORIA ARROYO PARTY",
        614.0: " KANG VELOSO MAYOR SA UNA",
        615.0: " COJUSIGCO PARTY",
        616.0: " OMPIA PARTY (GOV. OF LANAO DEL SUR)",
        617.0: " MAGDALO PARTY",
        618.0: " LITO OSMENA PARTY",
        619.0: " COROMINAS PARTY",
        620.0: " GROUP OF MIRIAM SANTIAGO",
        621.0: " MAYOR DODONG VILLABA",
        622.0: " INDEPENDENT",
        623.0: " PPC - PEOPLE POWER COALITION",
        624.0: " CEBU MAYOR PARTY",
        625.0: " TOMMY OSMENA PARTY",
        626.0: " BAYAN MUNA",
        627.0: " KUSOG",
        628.0: " ROCO PARTY",
        701.0: "KMT",
        702.0: " DPP",
        703.0: "NP",
        704.0: "PFP",
        705.0: "TIP",
        706.0: "Green parties",
        801.0: "Democrat",
        802.0: "Thai rak Thai",
        803.0: "Chat thai",
        804.0: "Chat Pattana",
        805.0: "Rassadorn",
        806.0: "Kuamwangmai",
        807.0: "Thai Motherland",
        808.0: "Seritham",
        809.0: "other",
    },
    "q064": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q066": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q068": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q069": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q074": {
        1.0: "Once",
        2.0: "More than once",
        9.0: "Never done",
        97.0: "Not Applicable",
        98.0: "don't know",
        99.0: "No Answer",
    },
    "q075": {
        1.0: "Once",
        2.0: "More than once",
        9.0: "Never done",
        97.0: "Not Applicable",
        98.0: "don't know",
        99.0: "No Answer",
    },
    "q076": {
        1.0: "Once",
        2.0: "More than once",
        9.0: "Never done",
        97.0: "Not Applicable",
        98.0: "don't know",
        99.0: "No Answer",
    },
    "q077": {
        1.0: "Once",
        2.0: "More than once",
        9.0: "Never done",
        97.0: "Not Applicable",
        98.0: "don't know",
        99.0: "No Answer",
    },
    "q098": {
        1.0: "Not at all satisfied",
        2.0: "Not very satisfied",
        3.0: "Fairly satisfied",
        4.0: "Very satisfied",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q104": {
        1.0: "Veryl dissatisfied",
        2.0: "Somewhat dissatisfied",
        3.0: "Somewhat satisfied",
        4.0: "Very satisfied",
        5.0: "Half and Half",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q113": {
        1.0: "Much worse",
        2.0: "Somewhat worse",
        3.0: "Much the same",
        4.0: "Somewhat better",
        5.0: "Much better than before",
        97.0: "Not Applicable",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q114": {
        1.0: "Almost everyone is corrupt",
        2.0: "Most officials are corrupt",
        3.0: "Not a lot of officials are corrupt",
        4.0: "Hardly anyone is involved",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q115": {
        1.0: "Almost everyone is corrupt",
        2.0: "Most officials are corrupt",
        3.0: "Not a lot of officials are corrupt",
        4.0: "Hardly anyone is involved",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q116": {
        1.0: "Yes",
        2.0: "No",
        97.0: "Not Applicable",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q119": {
        1.0: "Economic development is definitely more important",
        2.0: "Economic development is somewhat more important",
        3.0: "Democracy is somewhat more important",
        4.0: "Democracy is definitely more important",
        5.0: "They are both equally importment",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q121": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q123": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q125": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q126": {
        1.0: "Strongly disagree",
        2.0: "Somewhat disagree",
        3.0: "Somewhat agree",
        4.0: "Strongly agree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q127": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q130": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q131": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q132": {
        1.0: "Strongly disagree",
        2.0: "Somewhat disagree",
        3.0: "Somewhat agree",
        4.0: "Strongly agree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q133": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q134": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q135": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q136": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q137": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q138": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q139": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q140": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q142": {
        1.0: "Strongly disagree",
        2.0: "Somewhat disagree",
        3.0: "Somewhat agree",
        4.0: "Strongly agree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q143": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
    "q145": {
        1.0: "Strongly agree",
        2.0: "Somewhat agree",
        3.0: "Somewhat disagree",
        4.0: "Strongly disagree",
        98.0: "Don't know",
        99.0: "No answer",
    },
}

w2_newq_mapping = {}