var_to_order_mapper = {
    "q001": ["Very Bad", "Bad", "So so", "Good", "Very Good"],
    "q002": ["Much Worse", "A little Worse", "About the same", "A little Better", "Much Better"],
    "q003": ["Much Worse", "A little Worse", "About the same", "A little Better", "Much Better"],
    "q004": ["Very Bad", "Bad", "So so", "Good", "Very Good"],
    "q005": [
        "Much worse now",
        "A little worse now",
        "About the same",
        "A little better now",
        "Much better now",
    ],
    "q006": ["Much Worse", "A little Worse", "About the same", "A little Better", "Much Better"],
    "q007": ["None at all", "Not very much trust", "Quite a lot of trust", "A great deal of trust"],
    "q008": ["None at all", "Not very much trust", "Quite a lot of trust", "A great deal of trust"],
    "q009": ["None at all", "Not very much trust", "Quite a lot of trust", "A great deal of trust"],
    "q010": ["None at all", "Not very much trust", "Quite a lot of trust", "A great deal of trust"],
    "q011": ["None at all", "Not very much trust", "Quite a lot of trust", "A great deal of trust"],
    "q014": ["None at all", "Not very much trust", "Quite a lot of trust", "A great deal of trust"],
    "q016": ["None at all", "Not very much trust", "Quite a lot of trust", "A great deal of trust"],
    "q024": ["One can't be too careful in dealing with them", "Both", "Most people can be trusted"],
    "q024": ["One can't be too careful in dealing with them", "Both", "Most people can be trusted"],
    "q027": ["No", "Yes"],
    "q029": ["No", "Yes"],
    "q030": ["No", "Yes"],
    "q056": [
        "Not at all interested",
        "Not very interested",
        "Somewhat interested",
        "Very interested",
    ],
    "q061": ["No impact at all", "A little impact", "Quite some impact", "A great deal of impact"],
    "q064": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q066": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q068": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q069": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q074": ["Never done", "Once", "More than once"],
    "q075": ["Never done", "Once", "More than once"],
    "q076": ["Never done", "Once", "More than once"],
    "q098": ["Not at all satisfied", "Not very satisfied", "Fairly satisfied", "Very satisfied"],
    "q104": [
        "Veryl dissatisfied",
        "Somewhat dissatisfied",
        "Half and Half",
        "Somewhat satisfied",
        "Very satisfied",
    ],
    "q113": [
        "Much worse",
        "Somewhat worse",
        "Much the same",
        "Somewhat better",
        "Much better than before",
    ],
    "q114": [
        "Almost everyone is corrupt",
        "Most officials are corrupt",
        "Not a lot of officials are corrupt",
        "Hardly anyone is involved",
    ],
    "q116": ["No", "Yes"],
    "q119": [
        "Democracy is definitely more important",
        "Democracy is somewhat more important",
        "They are both equally importment",
        "Economic development is somewhat more important",
        "Economic development is definitely more important",
    ],
    "q121": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q123": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q125": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q126": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q127": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q130": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q131": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q132": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q133": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q134": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q135": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q136": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q137": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q138": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q139": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q140": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q142": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q143": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "q145": ["Strongly disagree", "Somewhat disagree", "Somewhat agree", "Strongly agree"],
    "education": [
        "No formal education",
        "Incomplete elementary school",
        "Complete elementary school",
        "Incomplete secondary school",
        "Complete secondary school",
        "Incomplete high school",
        "Complete high school",
        "Some university_college education",
        "University_college degree",
        "Post graduate degree",
    ],
}

