w1_var_to_order_mapper = {
    "q001": ["Very Bad", "Bad", "So so", "Good", "Very Good"],
    "q002": [
        "Much Worse",
        "A little Worse",
        "About the same",
        "A little Better",
        "Much Better",
    ],
    "q003": [
        "Much Worse",
        "A little Worse",
        "About the same",
        "A little Better",
        "Much Better",
    ],
    "q004": ["Very Bad", "Bad", "So so", "Good", "Very Good"],
    "q005": [
        "Much worse now",
        "A little worse now",
        "About the same",
        "A little better now",
        "Much better now",
    ],
    "q006": [
        "Much Worse",
        "A little Worse",
        "About the same",
        "A little Better",
        "Much Better",
    ],
    "q007": [
        "None at all",
        "Not very much trust",
        "Quite a lot of trust",
        "A great deal of trust",
    ],
    "q008": [
        "None at all",
        "Not very much trust",
        "Quite a lot of trust",
        "A great deal of trust",
    ],
    "q009": [
        "None at all",
        "Not very much trust",
        "Quite a lot of trust",
        "A great deal of trust",
    ],
    "q010": [
        "None at all",
        "Not very much trust",
        "Quite a lot of trust",
        "A great deal of trust",
    ],
    "q011": [
        "None at all",
        "Not very much trust",
        "Quite a lot of trust",
        "A great deal of trust",
    ],
    "q014": [
        "None at all",
        "Not very much trust",
        "Quite a lot of trust",
        "A great deal of trust",
    ],
    "q016": [
        "None at all",
        "Not very much trust",
        "Quite a lot of trust",
        "A great deal of trust",
    ],
    "q024": [
        "One can't be too careful in dealing with them",
        "Both",
        "Most people can be trusted",
    ],
    "q024": [
        "One can't be too careful in dealing with them",
        "Both",
        "Most people can be trusted",
    ],
    "q027": ["No", "Yes"],
    "q029": ["No", "Yes"],
    "q030": ["No", "Yes"],
    "q056": [
        "Not at all interested",
        "Not very interested",
        "Somewhat interested",
        "Very interested",
    ],
    "q061": [
        "No impact at all",
        "A little impact",
        "Quite some impact",
        "A great deal of impact",
    ],
    "q064": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q066": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q068": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q069": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q074": ["Never done", "Once", "More than once"],
    "q075": ["Never done", "Once", "More than once"],
    "q076": ["Never done", "Once", "More than once"],
    "q098": [
        "Not at all satisfied",
        "Not very satisfied",
        "Fairly satisfied",
        "Very satisfied",
    ],
    "q104": [
        "Veryl dissatisfied",
        "Somewhat dissatisfied",
        "Half and Half",
        "Somewhat satisfied",
        "Very satisfied",
    ],
    "q113": [
        "Much worse",
        "Somewhat worse",
        "Much the same",
        "Somewhat better",
        "Much better than before",
    ],
    "q114": [
        "Almost everyone is corrupt",
        "Most officials are corrupt",
        "Not a lot of officials are corrupt",
        "Hardly anyone is involved",
    ],
    "q116": ["No", "Yes"],
    "q119": [
        "Democracy is definitely more important",
        "Democracy is somewhat more important",
        "They are both equally importment",
        "Economic development is somewhat more important",
        "Economic development is definitely more important",
    ],
    "q121": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q123": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q125": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q126": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q127": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q130": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q131": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q132": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q133": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q134": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q135": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q136": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q137": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q138": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q139": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q140": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q142": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q143": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "q145": [
        "Strongly disagree",
        "Somewhat disagree",
        "Somewhat agree",
        "Strongly agree",
    ],
    "education": [
        "No formal education",
        "Incomplete elementary school",
        "Complete elementary school",
        "Incomplete secondary school",
        "Complete secondary school",
        "Incomplete high school",
        "Complete high school",
        "Some university_college education",
        "University_college degree",
        "Post graduate degree",
    ],
}

w2_var_to_order_mapper = {
    "q1": [
        "Very bad",
        "Bad",
        "So so (not good nor bad)",
        "Good",
        "Very good",
        "Can't choose",
        "Decline to answer",
    ],
    "q2": [
        "Much worse",
        "A little worse",
        "About the same",
        "A little better",
        "Much better",
        "Can't choose",
        "Decline to answer",
    ],
    "q3": [
        "Much worse",
        "A little worse",
        "About the same",
        "A little better",
        "Much better",
        "Can't choose",
        "Decline to answer",
    ],
    "q4": [
        "Very bad",
        "Bad",
        "So so (not good nor bad)",
        "Good",
        "Very good",
        "Can't choose",
        "Decline to answer",
    ],
    "q5": [
        "Much worse now",
        "A little worse now",
        "About the same",
        "A little better now",
        "Much better now",
        "Can't choose",
        "Decline to answer",
    ],
    "q6": [
        "Much worse",
        "A little worse",
        "About the same",
        "A little better",
        "Much better",
        "Can't choose",
        "Decline to answer",
    ],
    "q8": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q9": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q10": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q11": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q12": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q14": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q15": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q17": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q18": [
        "None at all",
        "Not Very Much Trust",
        "Quite a Lot of Trust",
        "A Great Deal of Trust",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q23": [
        "You must be very careful in dealing with people",
        "Most people can be trusted",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q38": ["Not applicable", "No", "Yes", "Can't choose", "Decline to answer"],
    "q40": ["Not applicable", "No", "Yes", "Can't choose", "Decline to answer"],
    "q41": ["Not applicable", "No", "Yes", "Can't choose", "Decline to answer"],
    "q49": [
        "Not at all interested",
        "Not very interested",
        "Somewhat interested",
        "Very interested",
        "No answer",
        "Can't choose",
        "Decline to answer",
    ],
    "q50": [
        "Practically never",
        "Not even once a week",
        "Once or twice a week",
        "Several times a week",
        "Everyday",
        "No Answer",
        "No answer",
        "Can't choose",
        "Decline to answer",
    ],
    "q53": [
        "No impact at all",
        "A little impact",
        "Quite some impact",
        "A great deal of impact",
        "No answer",
        "Can't choose",
        "Decline to answer",
    ],
    "q56": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q58": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q59": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q60": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q76": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q77": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q80": [
        "Once",
        "More than once",
        "Never",
        "No answer",
        "Can't choose",
        "Decline to answer",
    ],
    "q81": [
        "Once",
        "More than once",
        "Never",
        "No answer",
        "Can't choose",
        "Decline to answer",
    ],
    "q82": [
        "Once",
        "More than once",
        "Never",
        "No answer",
        "Can't choose",
        "Decline to answer",
    ],
    "q83": ["Once", "More than once", "Never", "Can't choose", "Decline to answer"],
    "q93": [
        "Not at all satisfied",
        "Not very satisfied",
        "Fairly satisfied",
        "Very satisfied",
        "Can't choose",
        "Decline to answer",
    ],
    "q99": [
        "Very satisfied",
        "Somewhat satisfied",
        "Somewhat dissatisfied",
        "Very dissatisfied",
        "No answer or can't understand",
        "Can't choose",
        "Decline to answer",
    ],
    "q111": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q117": [
        "Almost everyone is corrupt",
        "Most officials are corrupt",
        "Not a lot of officials are corrupt",
        "Hardly anyone is involved",
        "Can't choose",
        "Decline to answer",
    ],
    "q118": [
        "Almost everyone is corrupt",
        "Most officials are corrupt",
        "Not a lot of officials are corrupt",
        "Hardly anyone is involved",
        "Can't choose",
        "Decline to answer",
    ],
    "q119": [
        "Witnessed",
        "Never witnessed",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q123": [
        "Economic development is definitely more important",
        "Economic development is somewhat more important",
        "Democracy is somewhat more important",
        "Democracy is definitely more important",
        "They are both equally important",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q124": [
        "Strongly approve",
        "Approve",
        "Disapprove",
        "Strongly Disapprove",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q126": [
        "Strongly approve",
        "Approve",
        "Disapprove",
        "Strongly Disapprove",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q127": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q128": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q129": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q130": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q133": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q134": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q135": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q136": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q137": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q138": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q139": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q140": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q141": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q142": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
    "q144": [
        "Strongly agree",
        "Somewhat agree",
        "Somewhat disagree",
        "Strongly disagree",
        "Do not understand the question",
        "Can't choose",
        "Decline to answer",
    ],
}

