/* This SPSS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
/* The last line of this file contains the path to your output '.sav' file */

FILE HANDLE DATA / NAME=".\korea v4.2.dat" LRECL=267

DATA LIST FILE=DATA/
   COUNTRY 1                IDNUMBER 2-5             LEVEL1 6-7            
   LEVEL3 8                 YRSURVEY 9-12            SE002 13              
   SE003 14-15              SE003A 16-17             SE003B 18-21          
   SE004 22                 SE004A 23                SE005 24-25           
   SE005A 26-27             SE005B 28                SE006 29-30           
   SE006A 31-32             SE007 33                 SE008A 34             
   SE008B 35                SE009 36                 SE009D 37             
   SE009A 38                SE009B 39-40             SE009C 41             
   SE012A 42                SE012BKR 43              SE012A_1 44           
   SE012A_2 45              SE012A_3 46-47           SE014 48              
   SE016 49                 SE016A 50                SE017 51              
   RELIG1 52-53             FGNUM 54                 PGNUM 55              
   Q001 56                  Q002 57                  Q003 58               
   Q004 59                  Q005 60                  Q006 61               
   Q007 62                  Q008 63                  Q009 64               
   Q010 65                  Q011 66                  Q012 67               
   Q013 68                  Q014 69                  Q015 70               
   Q016 71                  Q017 72                  Q018 73               
   Q019 74-75               Q019_1 76-77             Q019_2 78-79          
   Q019_3 80-81             Q020 82-83               Q020_1 84-85          
   Q020_2 86-87             Q020_3 88-89             Q021 90-91            
   Q022 92                  Q023 93                  Q024 94               
   Q025 95                  Q026 96                  Q027 97               
   Q028 98-100              Q029 101                 Q030 102              
   Q031 103                 Q032 104                 Q033 105              
   Q034 106                 Q035 107                 Q036 108              
   Q037 109                 Q038 110                 Q039 111              
   Q040 112                 Q041 113                 Q042 114              
   Q043 115                 Q044 116                 Q045 117              
   Q046 118                 Q047 119                 Q048 120              
   Q049 121                 Q050 122                 Q051 123              
   Q052 124                 Q053 125                 Q054 126              
   Q055 127                 Q056 128                 Q057 129              
   Q057A 130                Q058 131                 Q059 132              
   Q060 133                 Q061 134                 Q062 135-137          
   Q063 138                 Q064 139                 Q065 140              
   Q066 141                 Q067 142                 Q068 143              
   Q069 144                 Q070 145                 Q071 146              
   Q072 147                 Q073 148                 Q074 149              
   Q075 150                 Q076 151                 Q077 152              
   Q078 153                 Q079 154                 Q080 155              
   Q081 156                 Q082 157                 Q083 158              
   Q084 159                 Q085 160                 Q086 161              
   Q087 162                 Q088 163                 Q089 164              
   Q090 165                 Q091 166                 Q092 167              
   Q093 168                 Q094 169                 Q095 170              
   Q096 171                 Q097_1 172-174           Q097_2 175-177        
   Q097_3 178-180           Q098 181                 Q099 182-183          
   Q100 184-185             Q101 186-187             Q102 188-189          
   Q103 190-191             Q104 192                 Q105 193              
   Q106 194                 Q107 195                 Q108 196              
   Q109 197                 Q110 198                 Q111 199              
   Q112 200                 Q113 201                 Q114 202              
   Q115 203                 Q116 204                 Q116E 205             
   Q117 206                 Q118 207                 Q119 208              
   Q120 209                 Q121 210                 Q122 211              
   Q123 212                 Q124 213                 Q125 214              
   Q126 215                 Q127 216                 Q128 217              
   Q129 218                 Q130 219                 Q131 220              
   Q132 221                 Q133 222                 Q134 223              
   Q135 224                 Q136 225                 Q137 226              
   Q138 227                 Q139 228                 Q140 229              
   Q141 230                 Q142 231                 Q143 232              
   Q144 233                 Q145 234                 Q146 235              
   Q147 236                 Q148 237                 IR001 238             
   IR002 239                IR002A 240               IR002B 241            
   IR002C 242               IR003 243                IR003A 244            
   IR004 245                IR005 246                IR006 247             
   IR007_1 248              IR007_2 249              IR007_3 250           
   IR008 251                IR009 252                IR010A 253            
   IR010B 254               IR010C 255               IR010D 256            
   IR010E 257               KR001 258                KR002 259             
   KR003 260                KR004 261-264            KR005 265-266         
   W_KR 267 .            

VARIABLE LABELS
   COUNTRY 'country  code'
   IDNUMBER 'ID number'
   LEVEL1 'Area'
   LEVEL3 'urban-rural'
   YRSURVEY 'Survey year'
   SE002 'Gender'
   SE003 'Age'
   SE003A 'Actual Age'
   SE003B 'Year of Birth'
   SE004 'Marital status'
   SE004A 'Marital Status(Y/N)'
   SE005 'Education'
   SE005A 'Education-yrs'
   SE005B 'Education(four categories)'
   SE006 'Religion'
   SE006A 'Religion(original)'
   SE007 'Religiosity'
   SE008A 'Size of household'
   SE008B 'Size of household-generation'
   SE009 'Monthly household income(10000 won)'
   SE009D 'annual income: urban and rural quintiles calculated separately'
   SE009A 'In the past 6 months in the course do an ordinary month, where' +
   ' does your personal income come from?where else?'
   SE009B 'Monthly household income-category(10000 won)'
   SE009C 'Monthly household income(original) (10000 won)'
   SE012A 'Main Occupation'
   SE012BKR 'Occupation(original)'
   SE012A_1 'Status of employment(K)'
   SE012A_2 'Occupation(1)'
   SE012A_3 'Occupation(2)'
   SE014 'language'
   SE016 'ethnicity'
   SE016A 'subjective ethnical identity'
   SE017 'Social class'
   RELIG1 'religion
'
   FGNUM 'formal group number
'
   PGNUM 'informal group number
'
   Q001 'How would you rate the overall economic condition of our country' +
   ' today?'
   Q002 'How would you describe the change in the economic condition of' +
   ' our country over the past five years?'
   Q003 "What do you think will be the state of our country's economic" +
   " condition five years from now?"
   Q004 'As for your own family, how do you rate your economic situation' +
   ' today?'
   Q005 'How would you compare the current economic condition of your' +
   ' family with what it was five years ago?'
   Q006 'What do you think the economic situation of your family will be' +
   ' five years from now?'
   Q007 'How much trust do you have in the courts?'
   Q008 'How much trust do you have in the national government?'
   Q009 'How much trust do you have in political parties?'
   Q010 'How much trust do you have in Parliament?'
   Q011 'How much trust do you have in civil service?'
   Q012 'How much trust do you have in the military?'
   Q013 'How much trust do you have in the police?'
   Q014 'How much trust do you have in local government?'
   Q015 'How much trust do you have in newspapers?'
   Q016 'How much trust do you have in television?'
   Q017 'How much trust do you have in the election commission?'
   Q018 'How much trust do you have in non-governmental organizations?'
   Q019 'Are you a member of any organization or formal groups?'
   Q019_1 'Which organizations or formal groups do you belong to(1st)?'
   Q019_2 'Which organizations or formal groups do you belong to(2nd)?'
   Q019_3 'Which organizations or formal groups do you belong to(3rd)?'
   Q020 'Are you a member of any private groups, circles or regular' +
   ' gatherings?'
   Q020_1 'The name of private group, circle or regular gatherings(1st)'
   Q020_2 'The name of private group, circle or regular gatherings(2nd)'
   Q020_3 'The name of private group, circle or regular gatherings(3rd)'
   Q021 'Which of these organizations or groups matters the most to' +
   ' you?
'
   Q022 'How frequently do you participate?'
   Q023 'How often do you discuss politics?'
   Q024 'most people can be trusted??'
   Q025 'I have enough friends and connections so that I can get help if I' +
   ' need it'
   Q026 "I have some friends with influence, so I don't have to worry too" +
   " much if I get into a tight spot"
   Q027 'Have you participated in last election?'
   Q028 'Which party did you vote for?'
   Q029 'Did you attend a campaign meeting or rally?'
   Q030 'Did you try to persuade others to vote for a certain candidate or' +
   ' party?'
   Q031 'Did you do anything else to help or show your support for a party' +
   ' or candidate running in the election?'
   Q032 'Asked to vote for a particular candidate?_FAMILY MEMBER/RELATIVE'
   Q033 'Asked following personally ask you to vote for a particular' +
   ' candidate?_SENIORS IN A CLAN OR EXTENDED FAMILY'
   Q034 'Asked to vote for a particular candidate?_NEIGHBOR/FRIEND'
   Q035 'Asked to vote for a particular candidate?_COMMUNITY LEADERS'
   Q036 'Asked to vote for a particular candidate?_SUPERIOR AT' +
   ' WORK/SCHOOL'
   Q037 'Asked to vote for a particular candidate?_OWNERS OF THE FIRM/UNIT' +
   ' THAT YOU WORK FOR'
   Q038 'Asked to vote for a particularcandidate?_MEMBER/OFFICIAL OF' +
   ' ORGANIZATION THAT YOU BELONG TO'
   Q039 'Asked to vote for a particular candidate?_GOVERNMENT OFFICIAL' +
   ' WHOM YOU KNOW PERSONALLY'
   Q040 "Asked to vote for a particular candidate?_GOVERNMENT OFFICIAL" +
   " WHOM YOU DON'T KNOW"
   Q041 'Asked to vote for a particular candidate?_CANDIDATE/PARTY' +
   ' ACTIVIST WHOM YOU KNOW PERSONALLY'
   Q042 'Asked to vote for a particular candidate?_CANDIDATE/PARTY' +
   ' ACTIVIST WHOM YOU DONT KNOW'
   Q043 'Asked to vote for a particular candidate?_OTHERS'
   Q044 'Influential_FAMILY MEMBER/RELATIVE'
   Q045 'Influential_SENIORS IN A CLAN OR EXTENDED FAMILY'
   Q046 'Influential_NEIGHBOR/FRIEND'
   Q047 'Influential_COMMUNITY LEADERS'
   Q048 'Influential_SUPERIOR AT WORK/SCHOOL'
   Q049 'Influential_OWNERS OF THE FIRM/UNIT THAT YOU WORK FOR'
   Q050 'Influential_MEMBER/OFFICIAL OF ORGANIZATION THAT YOU BELONG TO'
   Q051 'Influential_GOVERNMENT OFFICIAL WHOM YOU KNOW PERSONALLY'
   Q052 "Influential_GOVERNMENT OFFICIAL WHOM YOU DON'T KNOW"
   Q053 'Influential_CANDIDATE/PARTY ACTIVIST WHOM YOU KNOW PERSONALLY'
   Q054 "Influential_CANDIDATE/PARTY ACTIVIST WHOM YOU DON'T KNOW"
   Q055 'Influential_OTHERS'
   Q056 'How interested would you say you are interested in politics?'
   Q057 'How often do you follow news about politics?'
   Q058 'How often do you follow news about politics in the daily' +
   ' newspaper?'
   Q059 'How often do you follow news about politics on television?'
   Q060 'How often do you follow news about politics on the radio?'
   Q061 'How much impact do you feel government policies have on your' +
   ' daily life?'
   Q062 'party feel closest to'
   Q063 'closeness'
   Q064 "Even if parents' demands are unreasonable, children still should" +
   " do what they ask?"
   Q065 'When hiring someone, even if a stranger is more qualified, the' +
   ' opportunity should still be given to relatives and friend'
   Q066 'When one has a conflict with a neighbor, the best way to deal' +
   ' with it is to accommodate the other person?'
   Q067 'Wealth and poverty, success and failure are all determined by' +
   ' fate?'
   Q068 'A person should not insist on his own opinion if his co-workers' +
   ' disagree with him?'
   Q069 'For the sake of the family, the individual should put his' +
   ' personal interests second?'
   Q070 'A man will lose face if he works under a female supervisor?'
   Q071 'If there is a quarrel, we should ask an elder to resolve the' +
   ' dispute?'
   Q072 'When a mother-in-law and a daughter-in-law come into conflict,' +
   ' even if the mother-in-law is in the wrong, the husband sh'
   Q073 'Contacted any government official to express your opinions?'
   Q074 'Contacted officials to express your opinions at higher level?'
   Q075 'contacted elected legislative representatives at any level?'
   Q076 'Contacted political parties or other political organizations?'
   Q077 'Contacted non-government/civil society organizations?'
   Q078 'Contacted media to comment on something?'
   Q079 'Demonstrated, striken, or sat-in for something?'
   Q080 'Contacted other people?'
   Q081 'Did you do this alone or with others?_contacted government' +
   ' official'
   Q082 'Did you do this alone or with others?_contacted officials at' +
   ' higher level'
   Q083 'Did you do this alone or with others?_contacted elected' +
   ' legislative representatives at any level'
   Q084 'Did you do this alone or with others?_contacted political parties' +
   ' or other political organizations'
   Q085 'Did you do this alone or with others?_contacted no' +
   'n-government/civil society organizaions'
   Q086 'Did you do this alone or with others?_contacted media'
   Q087 'Did you do this alone or with others?_demonstration, strike,' +
   ' sit-in'
   Q088 'Did you do this alone or with others?_contacted other people'
   Q089 'Gift or dinner_contacted government'
   Q090 'Gift or dinner_contacted officials at highter level'
   Q091 'Gift or dinner_contacted elected legislative representatives'
   Q092 'Gift or dinner_contacted political parties or other political' +
   ' organizations'
   Q093 'Gift or dinner_contacted non-goverment/civil society' +
   ' organizations'
   Q094 'Gift or dinner_contacted media'
   Q095 'Gift or dinner_demonstration, strike, sit-in'
   Q096 'Gift or dinner_contacted other people'
   Q097_1 'what does democracy mean?(The first answer)'
   Q097_2 'what does democracy mean?(The second answer)'
   Q097_3 'what does democracy mean?(The third answer)'
   Q098 'Satisfaction with the way democracy works in our country?'
   Q099 'Where would you place our country before 1987?'
   Q100 'Where would you place our country under the present government?'
   Q101 'To what extent would you want our country to be democratic now?'
   Q102 'Where do you expect our country to be in five years?'
   Q103 'Do you think democracy is suitable for our country?'
   Q104 'How satisfied or dissatisfied are you with the current' +
   ' goverment?'
   Q105 'Everyone is free to say what they think- is better than before?'
   Q106 'Everyone is treated equally by the government- is better than' +
   ' before?'
   Q107 'People like me can have an influence on government- is better' +
   ' than before?'
   Q108 'Corruption in politics and government is under control- is better' +
   ' than before?'
   Q109 'The gap between the rich and the poor have narrowed- is better' +
   ' than before?'
   Q110 'Preventing crime and maintaining order- is better than before?'
   Q111 'Economic development- is better than before?'
   Q112 'Judges and courts are free from political interference- is better' +
   ' than before?'
   Q113 'You can join any organization you like- is better than before?'
   Q114 'How widespread corruption in your local/municipal government?'
   Q115 'How widespread corruption in the national government?'
   Q116 'anyone you know personally witnessed an act of corruption?'
   Q116E 'anyone you know personally witnessed '
   Q117 'Which comes closest to your own opinion?'
   Q118 'Which comes closer to your own view?'
   Q119 'choose between democracy and economic development?'
   Q120 'Which comes closer to your own view?'
   Q121 'We should get rid of parliament and elections and have a strong' +
   ' leader decide things'
   Q122 'No opposition party should be allowed to compete for power'
   Q123 'The military should come in to govern the country'
   Q124 'We should get rid of parliament and elections and have the' +
   ' experts decide everything'
   Q125 'It is ok for the government to disregard the law in order to deal' +
   ' with the situation, when the country is facing a diffi'
   Q126 'I have the ability to participate in politics'
   Q127 "Politics and government seems so complicated that a person like" +
   " me can't really understand what is going on"
   Q128 'The nation is run by a powerful few and ordinary citizens cannot' +
   ' do much about it'
   Q129 "People like me don't have any influence over what the government" +
   " does"
   Q130 'Our form of government is still the best for us'
   Q131 'You can generally trust the people who run our government to do' +
   ' what is right'
   Q132 'People with little or no education should have as much say in' +
   ' politics as highly-educated people'
   Q133 'Government leaders are like the head of a family; we should all' +
   ' follow their decisions'
   Q134 'The government should decide whether certain ideas should be' +
   ' allowed to be discussed in society'
   Q135 'Harmony of the community will be disrupted if people organize' +
   ' lots of groups'
   Q136 'When judges decide important cases, they should accept the view' +
   ' of the executive branch'
   Q137 'If the government is constantly checked by the legislature, it' +
   ' cannot possibly accomplish great things'
   Q138 'If we have political leaders who are morally upright, we can let' +
   ' them decide everything'
   Q139 'If people have too many different ways of thinking, society will' +
   ' be chaotic'
   Q140 'The government should maintain ownership of major state-owned' +
   ' enterprises'
   Q141 'The national government should have more authority over local' +
   ' decisions than it does now'
   Q142 'Our country should defend our way of life instead of becoming' +
   ' more and more like other countries'
   Q143 'For the sake of the national community/society, the individual' +
   ' should be prepared to sacrifice his personal interest'
   Q144 'The state is like a big machine and the individual is but a small' +
   ' cog, with no independent status'
   Q145 'The most important thing for a political leader is to accomplish' +
   ' his goals even if he has to ignore the established proc'
   Q146 'If a political leader really believes in his position, he should' +
   ' refuse to compromise regardless of how many people disa'
   Q147 'A political leader should tolerate the views of those who' +
   ' challenge his political ideals'
   Q148 'A political leader should not tolerate the views of those who' +
   ' challenge his political ideals'
   IR001 'Interviewer_s number'
   IR002 'Is this the first questionnaire the interviewer have completed?'
   IR002A 'Interviewer_s gender'
   IR002B 'Interviewer_s age'
   IR002C 'What kind of language do you normally use at home'
   IR003 'Presence of others other than the respondent while' +
   ' interviewing
'
   IR003A 'who were they?'
   IR004 'Has the respondent ever refused to be interviewed during the' +
   ' whole process?'
   IR005 'Has the respondent ever felt impatient during the interview?'
   IR006 'How cooperative was the respondent during the interview?'
   IR007_1 'date of interview: month'
   IR007_2 'date of interview: day'
   IR007_3 'date of interview: year'
   IR008 'Language in which interview was conducted'
   IR009 'Was the interview conducted with the assisance of an interpreter'
   IR010A "What is the condition of the road leading to interview's" +
   " residence"
   IR010B "How do rate the sanitary condition in the public area in the" +
   " interviewee's nearby neighborhood"
   IR010C "Tell us whetherthe interviewee's residence has public water" +
   " supply"
   IR010D "Tell us whetherthe interviewee's residence has electricity"
   IR010E "Walking distance between the nearest public transportation stop" +
   " and the respondent's house"
   KR001 'Connecting internet'
   KR002 'Following news on internet'
   KR003 'Size of community'
   KR004 'Year of Birth'
   KR005 'Place of brth'
.

VALUE LABELS
 COUNTRY
     3 'Korea' /
 LEVEL1
     1 'Seoul'
     2 'Pusan'
     3 'Taegu'
     4 'Inchon'
     5 'Kwangju'
     6 'Taejon'
     7 'Ulsan'
     8 'Kyonggi'
     9 'Kangwon'
     10 'Chungbuk'
     11 'Chungnam'
     12 'Chonbuk'
     13 'Chonnam'
     14 'Kyongbuk'
     15 'Kyongnam' /
 LEVEL3
     1 'urban'
     2 'rural' /
 YRSURVEY
     2003 '2003' /
 SE002
     1 'Male'
     2 'Female' /
 SE003
     1 '18-19'
     2 '20-24'
     3 '25-29'
     4 '30-34'
     5 '35-39'
     6 '40-44'
     7 '45-49'
     8 '50-54'
     9 '55-59'
     10 '60-70'
     11 '71-75'
     12 '76¥H¤W' /
 SE003A
     20 '20'
     21 '21'
     22 '22'
     23 '23'
     24 '24'
     25 '25'
     26 '26'
     27 '27'
     28 '28'
     29 '29'
     30 '30'
     31 '31'
     32 '32'
     33 '33'
     34 '34'
     35 '35'
     36 '36'
     37 '37'
     38 '38'
     39 '39'
     40 '40'
     41 '41'
     42 '42'
     43 '43'
     44 '44'
     45 '45'
     46 '46'
     47 '47'
     48 '48'
     49 '49'
     50 '50'
     51 '51'
     52 '52'
     53 '53'
     54 '54'
     55 '55'
     56 '56'
     57 '57'
     58 '58'
     59 '59'
     60 '60'
     61 '61'
     62 '62'
     63 '63'
     64 '64'
     65 '65'
     66 '66'
     67 '67'
     68 '68'
     69 '69'
     70 '70'
     71 '71'
     72 '72'
     73 '73'
     74 '74'
     75 '75'
     76 '76'
     77 '77'
     78 '78'
     79 '79'
     80 '80'
     81 '81'
     82 '82'
     83 '83'
     84 '84'
     85 '85'
     86 '86'
     87 '87'
     88 '88'
     89 '89'
     90 '90' /
 SE003B
     1918 '1918'
     1919 '1919'
     1921 '1921'
     1922 '1922'
     1923 '1923'
     1924 '1924'
     1925 '1925'
     1926 '1926'
     1927 '1927'
     1928 '1928'
     1929 '1929'
     1930 '1930'
     1931 '1931'
     1932 '1932'
     1933 '1933'
     1934 '1934'
     1935 '1935'
     1936 '1936'
     1937 '1937'
     1938 '1938'
     1939 '1939'
     1940 '1940'
     1941 '1941'
     1942 '1942'
     1943 '1943'
     1944 '1944'
     1945 '1945'
     1946 '1946'
     1947 '1947'
     1948 '1948'
     1949 '1949'
     1950 '1950'
     1951 '1951'
     1952 '1952'
     1953 '1953'
     1954 '1954'
     1955 '1955'
     1956 '1956'
     1957 '1957'
     1958 '1958'
     1959 '1959'
     1960 '1960'
     1961 '1961'
     1962 '1962'
     1963 '1963'
     1964 '1964'
     1965 '1965'
     1966 '1966'
     1967 '1967'
     1968 '1968'
     1969 '1969'
     1970 '1970'
     1971 '1971'
     1972 '1972'
     1973 '1973'
     1974 '1974'
     1975 '1975'
     1976 '1976'
     1977 '1977'
     1978 '1978'
     1979 '1979'
     1980 '1980'
     1981 '1981'
     1982 '1982'
     1983 '1983' /
 SE004
     1 'Married'
     2 'Living-in as married'
     3 'Widowed'
     4 'Separated'
     5 'Divorced'
     6 'Single'
     99 'No Answer' /
 SE004A
     1 'Yes'
     2 'No'
     99 'No Answer' /
 SE005
     1 'No formal education'
     2 'Incomplete primary'
     3 'Complete primary'
     4 'Incomplete middle'
     5 'Complete middle'
     6 'Incomplete high'
     7 'Complete high/in high'
     8 'Complete junior/incomplete univ'
     9 'Complete university'
     10 'Graduate school' /
 SE005A
     0 '0 year'
     1 '1 year'
     2 '2 years'
     3 '3 years'
     4 '4 years'
     5 '5 years'
     6 '6 years'
     7 '7 years'
     8 '8 years'
     9 '9 years'
     10 '10 years'
     11 '11 years'
     12 '12 years'
     13 '13 years'
     14 '14 years'
     15 '15 years'
     16 '16 years'
     17 '17 years'
     18 '18 years'
     19 '19 years'
     20 '20 years' /
 SE005B
     1 'illiterate'
     2 'primary education'
     3 'secondary education'
     4 'tertitary education'
     98 "Don't Know"
     99 'No Answer' /
 SE006
     1 'Shinto'
     2 'Daoism'
     3 'Other Folk Religio'
     4 'Born again'
     5 'Buddhism'
     6 'Hinduism'
     7 'Islam'
     8 'Roman Catholics'
     9 'Protestantism'
     10 'Others'
     11 'None' /
 SE006A
     1 'Catholic'
     2 'Protestant'
     3 'Buddhist'
     4 'Confucianism'
     5 'None'
     6 'Wonbuddhism'
     7 'Soka Gakkai'
     8 'Shamanism'
     9 'Jehovahs Witnesses'
     10 'Chondogyo' /
 SE007
     1 'Several times a day'
     2 'Once a day'
     3 'Several times a week'
     4 'Once a week'
     5 'Once a month/Several times a year'
     7 'Once a year'
     9 'Practically never'
     99 'No Answer' /
 SE008A
     1 '1 people'
     2 '2 people'
     3 '3 people'
     4 '4 people'
     5 '5 people'
     6 '6 people'
     7 '7 people'
     8 '8 people'
     9 '9 people'
     10 '10 people'
     11 '11 people'
     12 '12 people'
     13 '13 people'
     14 '14 people'
     15 '15 people'
     16 '16 people'
     17 '17 people'
     18 '18 people'
     19 '19 people'
     20 '20 people'
     99 'No Answer' /
 SE008B
     1 'One'
     2 'Two'
     3 'Three'
     4 'Four' /
 SE009
     1 'Less than 199'
     2 '200-299'
     3 '300-399'
     4 '400-499'
     5 '500&above'
     97 'Not applicable' /
 SE009B
     1 '50 >'
     2 '50- 99'
     3 '100- 149'
     4 '150- 199'
     5 '200- 249'
     6 '250- 299'
     7 '300- 349'
     8 '350- 399'
     9 '400- 449'
     10 '450- 499'
     11 '500- 549'
     12 '550- 599'
     13 '600 +'
     97 'Not Applicable'
     98 "Don't Know"
     99 'No Answer' /
 SE009C
     1 'Less than 99'
     2 '100-199'
     3 '200-299'
     4 '300-399'
     5 '400-499'
     6 '500-599'
     7 '600&above'
     97 'Not applicable' /
 SE012A
     1 'Admin/Manager'
     2 'Professional'
     3 'Clerical'
     4 'Sale'
     5 'Service'
     6 'Farmer'
     7 'Manual worker'
     8 'Not working'
     9 'Other'
     97 'Not Applicable'
     98 "Don't know"
     99 'No answer' /
 SE012BKR
     1 'Professional'
     2 'Administrative/managerial'
     3 'White-collar office worker/technicians'
     4 'Sales'
     5 'Services'
     6 'Blue-collar'
     7 'Agriculture/fishery'
     8 'Unemployed'
     9 'Unclassified' /
 SE012A_1
     1 'Employer'
     2 'Self-employed'
     3 'Employed without pay'
     4 'Full time employed'
     5 'Part time employed'
     97 'Not applicable'
     99 'No Answer' /
 SE012A_2
     1 'Professional'
     2 'Administrative/managerial'
     3 'White-collar office worker/technicians'
     4 'Sales'
     5 'Services'
     6 'Blue-collar'
     7 'Agriculture/fishery'
     8 'Unemployed'
     9 'Unclassified' /
 SE017
     1 'Upper class'
     2 'Upper middle class'
     3 'Middle class'
     4 'Lower middle class'
     5 'Lower class' /
 RELIG1
     3 'Other Religion(Falungon, Ikando, Confucianism )'
     5 'Buddhism'
     8 'Roman Catholics'
     9 'Protestantism'
     10 'Others'
     11 'None' /
 FGNUM
     0 'None'
     1 'One'
     2 'Two'
     3 'Three' /
 PGNUM
     0 'None'
     1 'One'
     2 'Two'
     3 'Three' /
 Q001
     1 'Very Bad'
     2 'Bad'
     3 'So so'
     4 'Good'
     5 'Very good'
     9 'No Answer' /
 Q002
     1 'Much worse'
     2 'A little worse'
     3 'About the same'
     4 'A little better'
     5 'Much better'
     9 'No Answer' /
 Q003
     1 'Much worse'
     2 'A little worse'
     3 'About the same'
     4 'A little better'
     5 'Much better'
     99 'No Answer' /
 Q004
     1 'Very bad'
     2 'Bad'
     3 'So so'
     4 'Good'
     5 'Very good'
     99 'No Answer' /
 Q005
     1 'Much worse'
     2 'A little worse'
     3 'About the same'
     4 'A little better'
     5 'Much better'
     99 'No Answer' /
 Q006
     1 'Much worse'
     2 'A little worse'
     3 'About the same'
     4 'A little better'
     5 'Much better'
     99 'No Answer' /
 Q007
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q008
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q009
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q010
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q011
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q012
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q013
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q014
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q015
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q016
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q018
     1 'None at all'
     2 'Not very much'
     3 'Quite a lot'
     4 'A great deal'
     99 'No Answer' /
 Q019
     1 'Member of organization or group'
     99 'Not a member of organization or group' /
 Q019_1
     1 'Residential association'
     2 'PTA'
     3 'Trade association'
     4 'Agricultural association'
     5 'Labor union'
     6 'Producer cooperative'
     7 'Consumer cooperative'
     8 'Volunteer group'
     9 'Citizen movement organization'
     10 'Religious group'
     11 'Alumni association'
     12 'Candidate support organization'
     13 'Political party'
     14 'Sports or leisure group'
     15 'Other formal associations'
     97 'Not applicable' /
 Q019_2
     1 'Residential association'
     2 'PTA'
     3 'Trade association'
     4 'Agricultural association'
     5 'Labor union'
     6 'Producer cooperative'
     7 'Consumer cooperative'
     8 'Volunteer group'
     9 'Citizen movement organization'
     10 'Religious group'
     11 'Alumni association'
     12 'Candidate support organization'
     13 'Political party'
     14 'Sports or leisure group'
     15 'Other formal associations'
     97 'Not applicable' /
 Q019_3
     1 'Residential association'
     2 'PTA'
     3 'Trade association'
     4 'Agricultural association'
     5 'Labor union'
     6 'Producer cooperative'
     7 'Consumer cooperative'
     8 'Volunteer group'
     9 'Citizen movement organization'
     10 'Religious group'
     11 'Alumni association'
     12 'Candidate support organization'
     13 'Political party'
     14 'Sports or leisure group'
     15 'Other formal associations'
     97 'Not applicable' /
 Q020
     1 'Member of organization or group'
     99 'Not a member of organization or group' /
 Q020_1
     51 'Circle of colleagues at work'
     52 'Group at learning place'
     53 'Circle related to hobbies'
     54 'Circle related to business'
     55 'Circle for information exchange'
     56 'Informal loan circle'
     57 'Informal alumni circle'
     58 'Other informal circles'
     59 'General social gathering'
     60 'Circle related to military service'
     61 'Informal home province circle'
     62 'School parent meeting'
     63 'Voluntary service circle'
     64 'Circle related to religion'
     65 'Family gathering'
     66 'Mutual aid circle'
     67 'Clan meeting'
     97 'Not applicable' /
 Q020_2
     51 'Circle of colleagues at work'
     52 'Group at learning place'
     53 'Circle related to hobbies'
     54 'Circle related to business'
     55 'Circle for information exchange'
     56 'Informal loan circle'
     57 'Informal alumni circle'
     58 'Other informal circles'
     59 'General social gathering'
     60 'Circle related to military service'
     61 'Informal home province circle'
     62 'School parent meeting'
     63 'Voluntary service circle'
     64 'Circle related to religion'
     65 'Family gathering'
     66 'Mutual aid circle'
     67 'Clan meeting'
     97 'Not applicable' /
 Q020_3
     51 'Circle of colleagues at work'
     52 'Group at learning place'
     53 'Circle related to hobbies'
     54 'Circle related to business'
     55 'Circle for information exchange'
     56 'Informal loan circle'
     57 'Informal alumni circle'
     58 'Other informal circles'
     59 'General social gathering'
     60 'Circle related to military service'
     61 'Informal home province circle'
     62 'School parent meeting'
     63 'Voluntary service circle'
     64 'Circle related to religion'
     65 'Family gathering'
     66 'Mutual aid circle'
     67 'Clan meeting'
     97 'Not applicable' /
 Q021
     1 'Residential association'
     2 'PTA'
     3 'Trade association'
     4 'Agricultural association'
     5 'Labor union'
     6 'Producer cooperative'
     7 'Consumer cooperative'
     8 'Volunteer group'
     9 'Citizen movement organization'
     10 'Religious group'
     11 'Alumni association'
     12 'Candidate support organization'
     13 'Political party'
     14 'Sports or leisure group'
     15 'Other formal associations'
     51 'Circle of colleagues at work'
     52 'Group at learning place'
     53 'Circle related to hobbies'
     54 'Circle related to business'
     55 'Circle for information exchange'
     56 'Informal loan circle'
     57 'Informal alumni circle'
     58 'Other informal circles'
     59 'General social gathering'
     60 'Circle related to military service'
     61 'Informal home province circle'
     62 'School parent meeting'
     63 'Voluntary service circle'
     64 'Circle related to religion'
     65 'Family gathering'
     66 'Mutual aid circle'
     67 'Clan meeting'
     97 'Not applicable' /
 Q022
     1 'Never'
     2 'Rarely'
     3 'Sometimes'
     4 'Often'
     5 'Very often'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q023
     1 'Never'
     2 'Rarely'
     3 'Sometimes'
     4 'Often'
     5 'Very often'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q024
     1 'One cannot be too careful'
     2 'Most people can be trusted'
     99 'No Answer' /
 Q025
     1 'Very well'
     2 'Pretty well'
     3 'Not very much'
     4 'Not at all'
     99 'No Answer' /
 Q027
     1 'No'
     2 'Yes'
     97 'Not applicable'
     98 'Do not remember'
     99 'No Answer' /
 Q028
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer'
     301 'Lee Hoi-chang'
     302 'Roh Moo-hyun'
     303 'Kwon Young-ghil'
     304 'Jang Se-Dong' /
 Q029
     1 'No'
     2 'Yes'
     99 'No Answer' /
 Q030
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q031
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q032
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q033
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q034
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q035
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q036
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q037
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q038
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q039
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q040
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q041
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q042
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q043
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q044
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q045
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q046
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q047
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q048
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q049
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q050
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q051
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q052
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q053
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q054
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q055
     1 'No'
     2 'Yes'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q056
     1 'Not at all'
     2 'A little'
     3 'Some'
     4 'Quite a lot' /
 Q057
     2 'Practically never'
     3 'Not even once a week'
     4 'Once or twice a week'
     5 'Several times a week'
     6 'Everyday' /
 Q058
     2 'Practically never'
     3 'Not even once a week'
     4 'Once or twice a week'
     5 'Several times a week'
     6 'Everyday' /
 Q059
     2 'Practically never'
     3 'Not even once a week'
     4 'Once or twice a week'
     5 'Several times a week'
     6 'Everyday' /
 Q060
     2 'Practically never'
     3 'Not even once a week'
     4 'Once or twice a week'
     5 'Several times a week'
     6 'Everyday' /
 Q061
     1 'Not at all'
     2 'A little'
     3 'Some'
     4 'A great deal'
     99 'No Answer' /
 Q062
     99 'None'
     301 'Democratic party'
     302 'Grand National party'
     303 'United Liberal Democrats'
     304 'Democratic Labor party'
     305 'Others' /
 Q063
     1 'A little'
     2 'Somewhat'
     3 'Very much'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q064
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q065
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q066
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q067
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q068
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q069
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q070
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q071
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q072
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q073
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q074
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q075
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q076
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q077
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q078
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q079
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q080
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q081
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q082
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q083
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q084
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q085
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q086
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q087
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q088
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q089
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q090
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q091
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q092
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q093
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q094
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q095
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q096
     1 'Once'
     2 'More than once'
     9 'Never done'
     99 'No Answer' /
 Q097_1
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_2
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q097_3
     97 '  No substance in answer'
     98 "Don't know"
     99 'No Response'
     100 'Interpreting democracy in generic (populist) terms'
     110 '	Popular sovereignty'
     111 'Government of the people'
     120 'Government by the People'
     121 'People as their own master'
     122 'Power of the people'
     130 'Government for the People'
     131 "Putting people's interest first"
     132 'Care for people'
     133 "Responsive to people's need"
     134 'Governing in the interest of general welfare'
     140 'Absence of non-democratic arrangements'
     141 'No dictator'
     142 'No repression'
     200 'Interpreting a democracy in terms of some key elements of li'
     210 'Freedom and Civil Liberty'
     211 'Freedom in general'
     212 'Freedom of speech/press/expression'
     213 'Freedom of association'
     214 'Political liberty'
     215 'Protection of individual/human rights'
     216 'Freedom from government repression'
     217 'Freedom of participation'
     218 'Freedom of belief'
     219 'Freedom of individual choice'
     220 'Political Equality'
     221 'One man one vote'
     222 'Equality before the law/justice'
     223 'Non discrimination'
     230 'Democratic Institutions and Process'
     231 'Election, popular vote or electoral choice'
     232 'Parliament'
     233 'Separation of power or check-and-balance'
     234 'Competitive party system'
     235 'Power rotation'
     236 'Rule of law'
     237 'Independent judicial'
     238 'Majority rule'
     239 'Respect for minority rights'
     250 'Participation and Citizen Empowerment'
     251 'Ability to change government'
     252 'Voting'
     253 'Direct participation'
     254 'Demonstration'
     255 "Voice one's concern"
     260 'Social Pluralism'
     261 'Open society'
     262 'Pluralist society'
     300 'Interpreting democracy in terms of social and economic syste'
     310 'Free Economy'
     311 'Free market'
     312 'Private properties/ownership'
     313 'Free and fair competition'
     314 'Personal economic opportunities'
     315 'No central planning'
     320 'Equality, Justice or Fraternity'
     321 'Social equality'
     322 'Social justice'
     323 'Fraternity'
     324 'Equality of opportunities'
     325 'Social rights or social entitlements'
     326 'Welfare state'
     327 'Socialism'
     328 'Worker participation'
     330 'Socio-Economic Performance'
     331 'Solve unemployment'
     332 ' Find anyone a job'
     333 'Providing social welfare'
     334 'Taking good care of the weak'
     400 'Interpreting democracy in terms of good government'
     410 'Good Governance'
     411 'Honesty'
     412 'Responsible'
     413 'Openness or transparent government'
     414 'Fair treatment'
     415 'Efficiency'
     416 'No corruption'
     417 'Law-biding government (rule by law)'
     418 'Social stability'
     419 'Law and order'
     420 'Reform in General'
     421 'Political reform'
     422 'Economic reform'
     500 'Interpreting democracy in term of individual behaviors'
     510 'Democratic Style'
     511 'Communication'
     512 'Compromise'
     513 'Rational'
     514 'Tolerance'
     515 'Taking into account all parties concerned'
     516 'Freedom within legal limits'
     517 "Respect for others' rights"
     518 'No extremism'
     520 'Duties'
     521 'Citizen duties'
     522 'Action within the limits of law'
     523 'Law-binding'
     530 'Individualism'
     531 'Respect for individual privacy'
     532 'Independence'
     533 'Self-reliance'
     534 "Having one's own views"
     535 'Self-responsibility'
     536 "Responsibility for one's own action/decision"
     540 'Trust'
     600 'Interpreting democracy in other broad and abstract terms'
     610 'Political System '
     611 'Governmental institution'
     612 'Decentralization (local self-government)'
     620 'Nationalism and Statism'
     621 'Better country'
     622 'Wealthy state'
     623 'National independence'
     624 'Development of elite'
     625 'Individual less important than nation'
     630 'Stable and Cohesive Society'
     631 'Patriotism'
     632 'Solidarity'
     633 'Harmony'
     634 'No chaos, anarchy or disorder'
     640 'Other Lofty Elements'
     641 'World peace'
     642 'The commonwealth of the world'
     700 'Conditions or Prerequisites for Democracy'
     710 'Gradualism'
     711 'Incremental'
     712 'It takes time'
     713 'No radicalism'
     720 'Prerequisites'
     721 'Democratic aptitude of citizens'
     722 'Economic condition'
     723 'Level education'
     724 "Fit our country's own conditions"
     800 'Evaluation of Democracy or Democratic Regime'
     810 'Positive Appraisal of Democracy in General'
     811 'The best or the better'
     812 'Progressive'
     813 'Universal acceptance'
     814 'Global trend'
     820 'Negative Appraisal of Democracy in General'
     821 'Corrupt'
     822 'Inefficient'
     823 'Unstable, chaotic, anarchy'
     824 'Conflict'
     825 'Lead to injustice'
     826 'Obstruct economic development'
     827 'Place too much on individual interests, the worst system'
     828 'Does not exist'
     829 'We cannot have democracy'
     840 "Positive Appraisal of One's Own Country's (Taiwan's) Dem"
     850 "Negative Appraisal of One's Own Country's (Taiwan's) Democra"
     900 ' Reference or Cognitive Association'
     910 'Country reference'
     911 'Like United States, United Kingdom, Japan, etc'
     912 'Not like North Korea, etc'
     920 'Political figures (e.g., Sun Yet-sun, Lee Teng-hui, Abra'
     921 'Political parties or groups (e.g., DPP, KMT, etc)'
     922 'Other associations (state, politics, society)' /
 Q098
     1 'Very dissatisfied'
     2 'Somewhat dissatisfied'
     3 'Somewhat satisfied'
     4 'Very satisfied'
     98 'Dont Know'
     99 'No Answer' /
 Q099
     1 '1 Complete dictatorship'
     10 '10 Complete democracy'
     97 'Not Applicable'
     98 "Don't Know"
     99 'No Answer' /
 Q100
     1 '1 Complete dictatorship'
     10 '10 Complete democracy'
     97 'Not Applicable'
     98 "Don't Know"
     99 'No Answer' /
 Q101
     1 '1 Complete dictatorship'
     10 '10 Complete democracy'
     97 'Not Applicable'
     98 "Don't Know"
     99 'No Answer' /
 Q102
     1 '1 Complete dictatorship'
     10 '10 Complete democracy'
     97 'Not Applicable'
     98 "Don't Know"
     99 'No Answer' /
 Q103
     1 '1 Complete dictatorship'
     10 '10 Complete democracy'
     97 'Not Applicable'
     98 "Don't Know"
     99 'No Answer' /
 Q104
     1 'Very dissatisfied'
     2 'Somewhat dissatisfied'
     3 'Somewhat satisfied'
     4 'Very satisfied'
     98 'Dont Know'
     99 'No Answer' /
 Q105
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q106
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q107
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q108
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q109
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q110
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q111
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q112
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q113
     1 'Much worse'
     2 'Somewhat worse'
     3 'About the same'
     4 'Somewhat better'
     5 'Much better'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q114
     1 'Almost everyone'
     2 'Many'
     3 'Some'
     4 'Hardly anyone'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q115
     1 'Almost everyone'
     2 'Many'
     3 'Some'
     4 'Hardly anyone'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q116
     1 'Yes'
     2 'No'
     98 "Don't know"
     99 'No answer' /
 Q116E
     1 'Personally'
     2 'Family member'
     3 'Friend'
     4 'None'
     99 'No Answer' /
 Q117
     1 'Dictatorship sometimes'
     2 "Don't matter"
     3 'Democracy always' /
 Q118
     1 'Democracy not capable'
     2 'Democracy capable'
     99 'No Answer' /
 Q119
     1 'Eco-far more'
     2 'Eco-somewhat more'
     3 'Dem-somewhat more'
     4 'Dem-far more'
     5 'Both equally' /
 Q121
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q122
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q123
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q124
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q125
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q126
     1 'Strongly disagree'
     2 'Somewhat disagree'
     3 'Somewhat agree'
     4 'Strongly agree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q127
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q128
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q129
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q130
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q131
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q132
     1 'Strongly disagree'
     2 'Somewhat disagree'
     3 'Somewhat agree'
     4 'Strongly agree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q133
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q134
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q135
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q136
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q137
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q138
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q139
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q140
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q141
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q142
     1 'Strongly disagree'
     2 'Somewhat disagree'
     3 'Somewhat agree'
     4 'Strongly agree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q143
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q144
     1 'Strongly disagree'
     2 'Somewhat disagree'
     3 'Somewhat agree'
     4 'Strongly agree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q145
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q146
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q147
     1 'Strongly disagree'
     2 'Somewhat disagree'
     3 'Somewhat agree'
     4 'Strongly agree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 Q148
     1 'Strongly agree'
     2 'Somewhat agree'
     3 'Somewhat disagree'
     4 'Strongly disagree'
     97 'Not Applicable'
     98 'Dont Know'
     99 'No Answer' /
 IR004
     1 'Yes. at the beginning'
     2 'Yes, in the middle'
     3 'Yes, at the end'
     4 'Never' /
 IR005
     1 'Never'
     2 'Occasionally'
     3 'Sometimes'
     4 'Always' /
 IR006
     1 'Highly cooperative'
     2 'Fairly cooperative'
     3 'Not very cooperative'
     9 'No Answer' /
 KR001
     1 'Everyday'
     2 'Several times a week'
     3 'Once or twice a week'
     4 'Not even once a week'
     5 'Practically never'
     9 'No answer' /
 KR002
     1 'Everyday'
     2 'Several times a week'
     3 'Once or twice a week'
     4 'Not even once a week'
     5 'Practically never'
     99 'No Answer' /
 KR003
     1 'Large city'
     2 'Medium/small city'
     3 'Town/rural area' /
 KR004
     1918 '1918'
     1919 '1919'
     1921 '1921'
     1922 '1922'
     1923 '1923'
     1924 '1924'
     1925 '1925'
     1926 '1926'
     1927 '1927'
     1928 '1928'
     1929 '1929'
     1930 '1930'
     1931 '1931'
     1932 '1932'
     1933 '1933'
     1934 '1934'
     1935 '1935'
     1936 '1936'
     1937 '1937'
     1938 '1938'
     1939 '1939'
     1940 '1940'
     1941 '1941'
     1942 '1942'
     1943 '1943'
     1944 '1944'
     1945 '1945'
     1946 '1946'
     1947 '1947'
     1948 '1948'
     1949 '1949'
     1950 '1950'
     1951 '1951'
     1952 '1952'
     1953 '1953'
     1954 '1954'
     1955 '1955'
     1956 '1956'
     1957 '1957'
     1958 '1958'
     1959 '1959'
     1960 '1960'
     1961 '1961'
     1962 '1962'
     1963 '1963'
     1964 '1964'
     1965 '1965'
     1966 '1966'
     1967 '1967'
     1968 '1968'
     1969 '1969'
     1970 '1970'
     1971 '1971'
     1972 '1972'
     1973 '1973'
     1974 '1974'
     1975 '1975'
     1976 '1976'
     1977 '1977'
     1978 '1978'
     1979 '1979'
     1980 '1980'
     1981 '1981'
     1982 '1982'
     1983 '1983' /
 KR005
     1 'Seoul'
     2 'Pusan'
     3 'Taegu'
     4 'Inchon'
     5 'Kwangju'
     6 'Taejon'
     7 'Ulsan'
     8 'Kyonggi'
     9 'Kwangwon'
     10 'Chungbuk'
     11 'Chungnam'
     12 'Chonbuk'
     13 'Chonnam'
     14 'Kyongbuk'
     15 'Kyongnam'
     16 'Cheju'
     17 'North Korea'
     18 'Abroad'
     99 'NA' / .

/* User Missing Value Specifications */
MISSING VALUES
  SE004 (99)               SE004A (99)              SE007 (99)             
  SE008A (99)              SE009 (97)               SE009B (97, 98, 99)    
  SE009C (97)              SE012A (0)               SE012A_1 (99, 97)      
  Q003 (99)                Q004 (99)                Q005 (99)              
  Q006 (99)                Q007 (99)                Q008 (99)              
  Q009 (99)                Q010 (99)                Q011 (99)              
  Q012 (99)                Q013 (99)                Q014 (99)              
  Q015 (99)                Q016 (99)                Q018 (99)              
  Q019_1 (97)              Q019_2 (97)              Q019_3 (97)            
  Q020_1 (97)              Q020_2 (97)              Q020_3 (97)            
  Q021 (97, 99)            Q022 (99, 98, 97)        Q023 (99, 98, 97)      
  Q024 (99, 98)            Q025 (99, 98)            Q026 (99, 98)          
  Q027 (97, 98, 99)        Q028 (97, 98, 99)        Q029 (97, 98, 99)      
  Q030 (97, 98, 99)        Q031 (97, 98, 99)        Q032 (97, 98, 99)      
  Q033 (97, 98, 99)        Q034 (97, 98, 99)        Q035 (97, 98, 99)      
  Q036 (97, 98, 99)        Q037 (97, 98, 99)        Q038 (97, 98, 99)      
  Q039 (97, 98, 99)        Q040 (97, 98, 99)        Q041 (97, 98, 99)      
  Q042 (97, 98, 99)        Q043 (97, 98, 99)        Q044 (97, 98, 99)      
  Q045 (97, 98, 99)        Q046 (97, 98, 99)        Q047 (97, 98, 99)      
  Q048 (97, 98, 99)        Q049 (97, 98, 99)        Q050 (97, 98, 99)      
  Q051 (97, 98, 99)        Q052 (97, 98, 99)        Q053 (97, 98, 99)      
  Q054 (97, 98, 99)        Q055 (97, 98, 99)        Q056 (97, 98, 99)      
  Q057 (97, 98, 99)        Q058 (97, 98, 99)        Q059 (97, 98, 99)      
  Q060 (97, 98, 99)        Q061 (97, 98, 99)        Q062 (97, 98, 99)      
  Q063 (97, 98, 99)        Q064 (97, 98, 99)        Q065 (97, 98, 99)      
  Q066 (97, 98, 99)        Q067 (97, 98, 99)        Q068 (97, 98, 99)      
  Q069 (97, 98, 99)        Q070 (97, 98, 99)        Q071 (97, 98, 99)      
  Q072 (97, 98, 99)        Q073 (97, 98, 99)        Q074 (97, 98, 99)      
  Q075 (97, 98, 99)        Q076 (97, 98, 99)        Q077 (97, 98, 99)      
  Q078 (97, 98, 99)        Q079 (97, 98, 99)        Q080 (97, 98, 99)      
  Q081 (97, 98, 99)        Q082 (97, 98, 99)        Q083 (97, 98, 99)      
  Q084 (97, 98, 99)        Q085 (97, 98, 99)        Q086 (97, 98, 99)      
  Q087 (97, 98, 99)        Q088 (97, 98, 99)        Q089 (97, 98, 99)      
  Q090 (97, 98, 99)        Q091 (97, 98, 99)        Q092 (97, 98, 99)      
  Q093 (97, 98, 99)        Q094 (97, 98, 99)        Q095 (97, 98, 99)      
  Q096 (97, 98, 99)        Q097_1 (97, 98, 99)      Q097_2 (97, 98, 99)    
  Q097_3 (97, 98, 99)      Q098 (99, 98, 97)        Q099 (99, 98, 97)      
  Q100 (99, 98, 97)        Q101 (99, 98, 97)        Q102 (99, 98, 97)      
  Q103 (99, 98, 97)        Q104 (98, 99)            Q105 (99, 98, 97)      
  Q106 (99, 98, 97)        Q107 (99, 98, 97)        Q108 (99, 98, 97)      
  Q109 (99, 98, 97)        Q110 (99, 98, 97)        Q111 (99, 98, 97)      
  Q112 (99, 98, 97)        Q113 (99, 98, 97)        Q114 (99, 98, 97)      
  Q115 (99, 98, 97)        Q116 (99)                Q116E (99, 98, 97)     
  Q117 (99, 98, 97)        Q118 (99, 98, 97)        Q119 (99, 98, 97)      
  Q120 (99, 98, 97)        Q121 (99, 98, 97)        Q122 (99, 98, 97)      
  Q123 (99, 98, 97)        Q124 (99, 98, 97)        Q125 (99, 98, 97)      
  Q126 (99, 98, 97)        Q127 (99, 98, 97)        Q128 (99, 98, 97)      
  Q129 (99, 98, 97)        Q130 (99, 98, 97)        Q131 (99, 98, 97)      
  Q132 (99, 98, 97)        Q133 (99, 98, 97)        Q134 (99, 98, 97)      
  Q135 (99, 98, 97)        Q136 (99, 98, 97)        Q137 (99, 98, 97)      
  Q138 (99, 98, 97)        Q139 (99, 98, 97)        Q140 (99, 98, 97)      
  Q141 (99, 98, 97)        Q142 (99, 98, 97)        Q143 (99, 98, 97)      
  Q144 (99, 98, 97)        Q145 (99, 98, 97)        Q146 (99, 98, 97)      
  Q147 (99, 98, 97)        Q148 (99, 98, 97)        IR007_1 (99)           
  IR007_2 (99)             IR007_3 (9999)           KR001 (9)              
  KR002 (99) .
         

SAVE OUTFILE='.\korea v4.2.sav'.
